"""Tests for leanstral_stub_recovery (placeholder detection + LaTeX lookup).

Tests that exercise the actual translator are gated behind `slow` markers so
the default suite stays hermetic."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from leanstral_stub_recovery import (
    PlaceholderBlock,
    _build_recovery_hint,
    _replace_placeholder_in_text,
    detect_placeholders,
    find_source_latex,
    recover_paper,
)


def _placeholder_lean(label: str = "thm:foo", name: str = "foo", reason: str = "claim_shape_mismatch:eq->ineq") -> str:
    return (
        "-- Auto-generated by arxiv_to_lean.py\n"
        "namespace ArxivPaper\n"
        "\n"
        f"-- [theorem] {label}\n"
        "-- Statement (LaTeX): Some truncated LaTeX...\n"
        f"-- Translation: BLOCKED — {reason}\n"
        "-- Attempted signature rejected by translation_acceptance_gate.\n"
        f"theorem {name} : False := by sorry\n"
        "\n"
        "end ArxivPaper\n"
    )


def test_detect_placeholders_finds_false_sorry() -> None:
    blocks = detect_placeholders(_placeholder_lean())
    assert len(blocks) == 1
    assert blocks[0].label == "thm:foo"
    assert blocks[0].name == "foo"
    assert "claim_shape_mismatch" in blocks[0].failure_reason


def test_detect_placeholders_finds_true_trivial() -> None:
    """`theorem foo : True := trivial` is also a placeholder pattern."""
    src = (
        "namespace ArxivPaper\n"
        "-- [theorem] thm:bar\n"
        "-- Statement (LaTeX): bar\n"
        "theorem bar : True := trivial\n"
        "end ArxivPaper\n"
    )
    blocks = detect_placeholders(src)
    assert len(blocks) == 1
    assert blocks[0].name == "bar"


def test_detect_placeholders_skips_real_theorems() -> None:
    src = (
        "namespace ArxivPaper\n"
        "-- [theorem] thm:real\n"
        "-- Statement (LaTeX): something\n"
        "theorem real_thm (n : Nat) : n + 0 = n := by simp\n"
        "end ArxivPaper\n"
    )
    blocks = detect_placeholders(src)
    assert blocks == []


def test_detect_placeholders_handles_multiple_blocks() -> None:
    src = (
        "namespace ArxivPaper\n"
        "-- [theorem] thm:a\n"
        "-- Statement (LaTeX): a\n"
        "theorem a : False := by sorry\n"
        "\n"
        "-- [theorem] thm:b\n"
        "-- Statement (LaTeX): b\n"
        "-- Translation: BLOCKED — lean_elaboration_failed\n"
        "theorem b : False := by sorry\n"
        "\n"
        "-- [theorem] thm:c\n"
        "theorem c (x : Nat) : x = x := rfl\n"
        "end ArxivPaper\n"
    )
    blocks = detect_placeholders(src)
    assert [b.name for b in blocks] == ["a", "b"]


def test_recovery_hint_for_claim_shape_mismatch() -> None:
    h = _build_recovery_hint("claim_shape_mismatch:eq->ineq")
    assert "claim-shape mismatch" in h.lower()
    assert "equation" in h.lower() and "inequality" in h.lower()


def test_recovery_hint_for_lean_elaboration_failed() -> None:
    h = _build_recovery_hint("lean_elaboration_failed")
    assert "elaboration" in h.lower()
    assert "mathlib" in h.lower()


def test_recovery_hint_unknown_reason_falls_back_to_quoted_reason() -> None:
    h = _build_recovery_hint("some_brand_new_reason")
    assert "BLOCKED" in h
    assert "some_brand_new_reason" in h


def test_recovery_hint_empty_returns_empty() -> None:
    assert _build_recovery_hint("") == ""


def test_find_source_latex_returns_empty_when_missing(tmp_path: Path) -> None:
    latex, meta = find_source_latex("9999.99999", "thm:nonexistent", tmp_path)
    assert latex == ""
    assert meta == {}


def test_find_source_latex_reads_extracted_theorems(tmp_path: Path) -> None:
    """The lookup walks the canonical `extracted_theorems.json` paths and
    matches by label."""
    paper = "1234.56789"
    repo = tmp_path / "reproducibility" / "paper_agnostic_golden10_results" / paper
    repo.mkdir(parents=True)
    (repo / "extracted_theorems.json").write_text(json.dumps({
        "paper_id": paper,
        "entries": [
            {"label": "thm:foo", "statement": "If $x>0$ then $x+1>0$.", "source_file": "out.tex"},
            {"label": "thm:bar", "statement": "bar body", "source_file": "out.tex"},
        ],
    }), encoding="utf-8")
    latex, meta = find_source_latex(paper, "thm:foo", tmp_path)
    assert "x>0" in latex
    assert meta["source_file"] == "out.tex"


def test_replace_placeholder_in_text_swaps_signature() -> None:
    lean = _placeholder_lean(name="foo")
    block = detect_placeholders(lean)[0]
    new_sig = "theorem foo (n : Nat) : n + 0 = n"
    out = _replace_placeholder_in_text(lean, block, new_sig)
    assert "theorem foo (n : Nat) : n + 0 = n := by sorry" in out
    assert "theorem foo : False" not in out


def test_replace_placeholder_preserves_block_comments() -> None:
    """Comments around the placeholder (theorem header, LaTeX, BLOCKED) must
    survive the replacement — they're useful provenance for downstream tools."""
    lean = _placeholder_lean(label="thm:keep", name="keep")
    block = detect_placeholders(lean)[0]
    out = _replace_placeholder_in_text(lean, block, "theorem keep (x : Nat) : x = x")
    assert "-- [theorem] thm:keep" in out
    assert "-- Statement (LaTeX): Some truncated LaTeX..." in out
    assert "-- Translation: BLOCKED" in out


def test_recover_paper_dry_run_no_lean_file(tmp_path: Path) -> None:
    summary = recover_paper("9999.99999", project_root=tmp_path, write=False)
    assert summary["lean_file_missing"] is True
    assert summary["recovered"] == 0


def test_recover_paper_dry_run_reports_placeholders(tmp_path: Path) -> None:
    """Without --write, the tool only previews what it would attempt; no
    Mistral calls happen and no files mutate."""
    paper = "1234.56789"
    out_dir = tmp_path / "output"
    out_dir.mkdir()
    lean_path = out_dir / f"{paper}.lean"
    lean_path.write_text(_placeholder_lean(), encoding="utf-8")
    # Provide a source LaTeX so `would_attempt` is True.
    repo = tmp_path / "reproducibility" / "paper_agnostic_golden10_results" / paper
    repo.mkdir(parents=True)
    (repo / "extracted_theorems.json").write_text(json.dumps({
        "entries": [{"label": "thm:foo", "statement": "If x>0 then x+1>0."}],
    }), encoding="utf-8")

    summary = recover_paper(paper, project_root=tmp_path, write=False)
    assert summary["dry_run"] is True
    assert summary["placeholders_detected"] == 1
    assert summary["results"][0]["label"] == "thm:foo"
    assert summary["results"][0]["would_attempt"] is True
    # File was not modified.
    assert lean_path.read_text() == _placeholder_lean()
