/-
# PaperAlignmentsAuto2 — auto-generated trivial alignments (extension).

Generated by `scripts/auto_align_proposer.py`. Every theorem below
is a definitional equality between a paper-local stub and its
Mathlib counterpart (the stub's own RHS). Lake-verified before
registration in `output/corpus/alignments.json`.
-/

import Mathlib
import Desol.PaperTheory.Paper_1701_01421
import Desol.PaperTheory.Paper_2012_11433

namespace Desol.PaperAlignments2

theorem p_1701_01421_acknowledgements_10_aligned : Paper_1701_01421.acknowledgements_10 = (0 : ℝ) := rfl
theorem p_2012_11433_mu_C_aligned : Paper_2012_11433.mu_C = (0 : ℝ) := rfl

end Desol.PaperAlignments2
