/-
# PaperAlignmentsAuto — auto-generated trivial alignments.

Generated by `scripts/generate_trivial_alignments.py`. Each theorem here
is a definitional equality between a paper-theory stub
(`def Paper_X.foo : ℝ := 0`) and its trivial Mathlib counterpart
(`(0 : ℝ)`, `Set.univ`, `True`). The proof is `rfl` for every theorem.

These theorems back the corresponding entries in
`output/corpus/alignments.json`. Re-run the generator to refresh.
-/

import Mathlib
import Desol.PaperTheory.Paper_2012_09271
import Desol.PaperTheory.Paper_2304_09598
import Desol.PaperTheory.Paper_2604_21314
import Desol.PaperTheory.Paper_2604_21583
import Desol.PaperTheory.Paper_2604_21616
import Desol.PaperTheory.Paper_2604_21821
import Desol.PaperTheory.Paper_2604_21884

namespace Desol.PaperAlignments

-- (Generator output is appended below this comment by
-- `scripts/generate_trivial_alignments.py --out-lean ...`)

-- Auto-generated trivial alignments for 2304.09598
theorem p_2304_09598_C_eq_zero : Paper_2304_09598.C = (0 : ℝ) := rfl
theorem p_2304_09598_a_eq_zero : Paper_2304_09598.a = (0 : ℝ) := rfl
theorem p_2304_09598_alpha_1_eq_zero : Paper_2304_09598.alpha_1 = (0 : ℝ) := rfl
theorem p_2304_09598_b_1_eq_zero : Paper_2304_09598.b_1 = (0 : ℝ) := rfl
theorem p_2304_09598_b_2_eq_zero : Paper_2304_09598.b_2 = (0 : ℝ) := rfl
theorem p_2304_09598_defin_1_eq_zero : Paper_2304_09598.defin_1 = (0 : ℝ) := rfl
theorem p_2304_09598_defin_14_eq_zero : Paper_2304_09598.defin_14 = (0 : ℝ) := rfl
theorem p_2304_09598_e_1_eq_zero : Paper_2304_09598.e_1 = (0 : ℝ) := rfl
theorem p_2304_09598_e_2_eq_zero : Paper_2304_09598.e_2 = (0 : ℝ) := rfl
theorem p_2304_09598_h_and_are_ladder_multisegments_1_eq_zero : Paper_2304_09598.h_and_are_ladder_multisegments_1 = (0 : ℝ) := rfl
theorem p_2304_09598_h_dual_multisegments_respectively_2_eq_zero : Paper_2304_09598.h_dual_multisegments_respectively_2 = (0 : ℝ) := rfl
theorem p_2304_09598_h_is_a_ladder_multisegment_1_eq_zero : Paper_2304_09598.h_is_a_ladder_multisegment_1 = (0 : ℝ) := rfl
theorem p_2304_09598_h_is_a_multisegment_formed_by__1_eq_zero : Paper_2304_09598.h_is_a_multisegment_formed_by__1 = (0 : ℝ) := rfl
theorem p_2304_09598_h_is_a_simple_multisegment_1_eq_zero : Paper_2304_09598.h_is_a_simple_multisegment_1 = (0 : ℝ) := rfl
theorem p_2304_09598_h_is_simple_1_eq_zero : Paper_2304_09598.h_is_simple_1 = (0 : ℝ) := rfl
theorem p_2304_09598_h_l_l_3_eq_zero : Paper_2304_09598.h_l_l_3 = (0 : ℝ) := rfl
theorem p_2304_09598_h_label_prop_actions_let_delta_1_eq_zero : Paper_2304_09598.h_label_prop_actions_let_delta_1 = (0 : ℝ) := rfl
theorem p_2304_09598_h_multisegment_1_eq_zero : Paper_2304_09598.h_multisegment_1 = (0 : ℝ) := rfl
theorem p_2304_09598_h_multisegments_1_eq_zero : Paper_2304_09598.h_multisegments_1 = (0 : ℝ) := rfl
theorem p_2304_09598_h_n_n_3_eq_zero : Paper_2304_09598.h_n_n_3 = (0 : ℝ) := rfl
theorem p_2304_09598_h_rank_equal_defined_inside_1_eq_zero : Paper_2304_09598.h_rank_equal_defined_inside_1 = (0 : ℝ) := rfl
theorem p_2304_09598_h_source_2_2_eq_zero : Paper_2304_09598.h_source_2_2 = (0 : ℝ) := rfl
theorem p_2304_09598_h_source_3_3_eq_zero : Paper_2304_09598.h_source_3_3 = (0 : ℝ) := rfl
theorem p_2304_09598_kern7_eq_zero : Paper_2304_09598.kern7 = (0 : ℝ) := rfl
theorem p_2304_09598_r_i_1_j_eq_zero : Paper_2304_09598.r_i_1_j = (0 : ℝ) := rfl
theorem p_2304_09598_r_i_1_j_1_eq_zero : Paper_2304_09598.r_i_1_j_1 = (0 : ℝ) := rfl
theorem p_2304_09598_r_i_j_1_eq_zero : Paper_2304_09598.r_i_j_1 = (0 : ℝ) := rfl
theorem p_2304_09598_raise4_eq_zero : Paper_2304_09598.raise4 = (0 : ℝ) := rfl
theorem p_2304_09598_raise7_eq_zero : Paper_2304_09598.raise7 = (0 : ℝ) := rfl
theorem p_2304_09598_utf8_eq_zero : Paper_2304_09598.utf8 = (0 : ℝ) := rfl
theorem p_2304_09598_IrreducibleLadderMultisegment_eq_zero : Paper_2304_09598.IrreducibleLadderMultisegment = Set.univ := rfl

-- Auto-generated trivial alignments for 2604.21314
theorem p_2604_21314_infty_eq_zero : Paper_2604_21314.infty = (0 : ℝ) := rfl
theorem p_2604_21314_C_eq_zero : Paper_2604_21314.C = (0 : ℝ) := rfl
theorem p_2604_21314_a_eq_zero : Paper_2604_21314.a = (0 : ℝ) := rfl
theorem p_2604_21314_alpha_0_eq_zero : Paper_2604_21314.alpha_0 = (0 : ℝ) := rfl
theorem p_2604_21314_alpha_F_eq_zero : Paper_2604_21314.alpha_F = (0 : ℝ) := rfl
theorem p_2604_21314_defn_8_eq_zero : Paper_2604_21314.defn_8 = (0 : ℝ) := rfl
theorem p_2604_21314_h0_eq_zero : Paper_2604_21314.h0 = (0 : ℝ) := rfl
theorem p_2604_21314_h1_eq_zero : Paper_2604_21314.h1 = (0 : ℝ) := rfl
theorem p_2604_21314_h2_eq_zero : Paper_2604_21314.h2 = (0 : ℝ) := rfl
theorem p_2604_21314_h3_eq_zero : Paper_2604_21314.h3 = (0 : ℝ) := rfl
theorem p_2604_21314_h4_eq_zero : Paper_2604_21314.h4 = (0 : ℝ) := rfl
theorem p_2604_21314_h5_eq_zero : Paper_2604_21314.h5 = (0 : ℝ) := rfl
theorem p_2604_21314_h6_eq_zero : Paper_2604_21314.h6 = (0 : ℝ) := rfl
theorem p_2604_21314_hH_eps_eq_zero : Paper_2604_21314.hH_eps = (0 : ℝ) := rfl
theorem p_2604_21314_hT_eps_eq_zero : Paper_2604_21314.hT_eps = (0 : ℝ) := rfl
theorem p_2604_21314_hT_max_eq_zero : Paper_2604_21314.hT_max = (0 : ℝ) := rfl
theorem p_2604_21314_hfL1_eq_zero : Paper_2604_21314.hfL1 = (0 : ℝ) := rfl
theorem p_2604_21314_hu0_eq_zero : Paper_2604_21314.hu0 = (0 : ℝ) := rfl
theorem p_2604_21314_hz1_eq_zero : Paper_2604_21314.hz1 = (0 : ℝ) := rfl
theorem p_2604_21314_hz2_eq_zero : Paper_2604_21314.hz2 = (0 : ℝ) := rfl
theorem p_2604_21314_int_0_eq_zero : Paper_2604_21314.int_0 = (0 : ℝ) := rfl
theorem p_2604_21314_longrightarrow0_eq_zero : Paper_2604_21314.longrightarrow0 = (0 : ℝ) := rfl
theorem p_2604_21314_mX_i_eq_zero : Paper_2604_21314.mX_i = (0 : ℝ) := rfl
theorem p_2604_21314_mt0_eq_zero : Paper_2604_21314.mt0 = (0 : ℝ) := rfl
theorem p_2604_21314_nabla_H_eq_zero : Paper_2604_21314.nabla_H = (0 : ℝ) := rfl
theorem p_2604_21314_oza3_eq_zero : Paper_2604_21314.oza3 = (0 : ℝ) := rfl
theorem p_2604_21314_p_F_eq_zero : Paper_2604_21314.p_F = (0 : ℝ) := rfl
theorem p_2604_21314_phi_1_eq_zero : Paper_2604_21314.phi_1 = (0 : ℝ) := rfl
theorem p_2604_21314_phi_2_eq_zero : Paper_2604_21314.phi_2 = (0 : ℝ) := rfl
theorem p_2604_21314_s10_eq_zero : Paper_2604_21314.s10 = (0 : ℝ) := rfl
theorem p_2604_21314_s3_eq_zero : Paper_2604_21314.s3 = (0 : ℝ) := rfl
theorem p_2604_21314_theta_eq_zero : Paper_2604_21314.theta = (0 : ℝ) := rfl
theorem p_2604_21314_u0_eq_zero : Paper_2604_21314.u0 = (0 : ℝ) := rfl
theorem p_2604_21314_u_0_eq_zero : Paper_2604_21314.u_0 = (0 : ℝ) := rfl
theorem p_2604_21314_utf8_eq_zero : Paper_2604_21314.utf8 = (0 : ℝ) := rfl
theorem p_2604_21314_v_0_eq_zero : Paper_2604_21314.v_0 = (0 : ℝ) := rfl
theorem p_2604_21314_x_1_eq_zero : Paper_2604_21314.x_1 = (0 : ℝ) := rfl
theorem p_2604_21314_x_N_eq_zero : Paper_2604_21314.x_N = (0 : ℝ) := rfl
theorem p_2604_21314_y_1_eq_zero : Paper_2604_21314.y_1 = (0 : ℝ) := rfl
theorem p_2604_21314_y_N_eq_zero : Paper_2604_21314.y_N = (0 : ℝ) := rfl
theorem p_2604_21314_z1_eq_zero : Paper_2604_21314.z1 = (0 : ℝ) := rfl
theorem p_2604_21314_z2_eq_zero : Paper_2604_21314.z2 = (0 : ℝ) := rfl
theorem p_2604_21314_z_1_eq_zero : Paper_2604_21314.z_1 = (0 : ℝ) := rfl
theorem p_2604_21314_z_2_eq_zero : Paper_2604_21314.z_2 = (0 : ℝ) := rfl
theorem p_2604_21314_VolterraEstimateStatement_eq_zero : Paper_2604_21314.VolterraEstimateStatement = True := rfl

-- Auto-generated trivial alignments for 2604.21583
theorem p_2604_21583_C_eq_zero : Paper_2604_21583.C = (0 : ℝ) := rfl
theorem p_2604_21583_a_eq_zero : Paper_2604_21583.a = (0 : ℝ) := rfl
theorem p_2604_21583_alpha1_eq_zero : Paper_2604_21583.alpha1 = (0 : ℝ) := rfl
theorem p_2604_21583_assumption_slot_1_anchor_missing_eq_zero : Paper_2604_21583.assumption_slot_1_anchor_missing = (0 : ℝ) := rfl
theorem p_2604_21583_com1_eq_zero : Paper_2604_21583.com1 = (0 : ℝ) := rfl
theorem p_2604_21583_d_0_eq_zero : Paper_2604_21583.d_0 = (0 : ℝ) := rfl
theorem p_2604_21583_d_0_P_eq_zero : Paper_2604_21583.d_0_P = (0 : ℝ) := rfl
theorem p_2604_21583_d_P_eq_zero : Paper_2604_21583.d_P = (0 : ℝ) := rfl
theorem p_2604_21583_h1_eq_zero : Paper_2604_21583.h1 = (0 : ℝ) := rfl
theorem p_2604_21583_h2_eq_zero : Paper_2604_21583.h2 = (0 : ℝ) := rfl
theorem p_2604_21583_h3_eq_zero : Paper_2604_21583.h3 = (0 : ℝ) := rfl
theorem p_2604_21583_h4_eq_zero : Paper_2604_21583.h4 = (0 : ℝ) := rfl
theorem p_2604_21583_hB9_eq_zero : Paper_2604_21583.hB9 = (0 : ℝ) := rfl
theorem p_2604_21583_hB_rel_eq_zero : Paper_2604_21583.hB_rel = (0 : ℝ) := rfl
theorem p_2604_21583_hC_beta_eq_zero : Paper_2604_21583.hC_beta = (0 : ℝ) := rfl
theorem p_2604_21583_hC_m_eq_zero : Paper_2604_21583.hC_m = (0 : ℝ) := rfl
theorem p_2604_21583_hC_q_eq_zero : Paper_2604_21583.hC_q = (0 : ℝ) := rfl
theorem p_2604_21583_hC_t_eq_zero : Paper_2604_21583.hC_t = (0 : ℝ) := rfl
theorem p_2604_21583_hH1_eq_zero : Paper_2604_21583.hH1 = (0 : ℝ) := rfl
theorem p_2604_21583_hH2_eq_zero : Paper_2604_21583.hH2 = (0 : ℝ) := rfl
theorem p_2604_21583_hK_pos_eq_zero : Paper_2604_21583.hK_pos = (0 : ℝ) := rfl
theorem p_2604_21583_hQ1_eq_zero : Paper_2604_21583.hQ1 = (0 : ℝ) := rfl
theorem p_2604_21583_hR1_eq_zero : Paper_2604_21583.hR1 = (0 : ℝ) := rfl
theorem p_2604_21583_hV_bound_eq_zero : Paper_2604_21583.hV_bound = (0 : ℝ) := rfl
theorem p_2604_21583_hV_nonneg_eq_zero : Paper_2604_21583.hV_nonneg = (0 : ℝ) := rfl
theorem p_2604_21583_hZ0_eq_zero : Paper_2604_21583.hZ0 = (0 : ℝ) := rfl
theorem p_2604_21583_h_B9_disappears_eq_zero : Paper_2604_21583.h_B9_disappears = (0 : ℝ) := rfl
theorem p_2604_21583_h_Tr__eq_zero : Paper_2604_21583.h_Tr_ = (0 : ℝ) := rfl
theorem p_2604_21583_h_Tr_Hs2_eq_zero : Paper_2604_21583.h_Tr_Hs2 = (0 : ℝ) := rfl
theorem p_2604_21583_h_bound1_eq_zero : Paper_2604_21583.h_bound1 = (0 : ℝ) := rfl
theorem p_2604_21583_h_bound2_eq_zero : Paper_2604_21583.h_bound2 = (0 : ℝ) := rfl
theorem p_2604_21583_h_s1_small_eq_zero : Paper_2604_21583.h_s1_small = (0 : ℝ) := rfl
theorem p_2604_21583_h_s1_sufficiently_small_eq_zero : Paper_2604_21583.h_s1_sufficiently_small = (0 : ℝ) := rfl
theorem p_2604_21583_h_s2_close_eq_zero : Paper_2604_21583.h_s2_close = (0 : ℝ) := rfl
theorem p_2604_21583_h_s2_sufficiently_close_eq_zero : Paper_2604_21583.h_s2_sufficiently_close = (0 : ℝ) := rfl
theorem p_2604_21583_h_trace_H_eq_zero : Paper_2604_21583.h_trace_H = (0 : ℝ) := rfl
theorem p_2604_21583_ha1_eq_zero : Paper_2604_21583.ha1 = (0 : ℝ) := rfl
theorem p_2604_21583_halpha1_eq_zero : Paper_2604_21583.halpha1 = (0 : ℝ) := rfl
theorem p_2604_21583_hbeta_gt_32_eq_zero : Paper_2604_21583.hbeta_gt_32 = (0 : ℝ) := rfl
theorem p_2604_21583_hbeta_le_1_eq_zero : Paper_2604_21583.hbeta_le_1 = (0 : ℝ) := rfl
theorem p_2604_21583_hbeta_le_12_eq_zero : Paper_2604_21583.hbeta_le_12 = (0 : ℝ) := rfl
theorem p_2604_21583_hbeta_le_32_eq_zero : Paper_2604_21583.hbeta_le_32 = (0 : ℝ) := rfl
theorem p_2604_21583_hmu0_eq_zero : Paper_2604_21583.hmu0 = (0 : ℝ) := rfl
theorem p_2604_21583_hs1_eq_zero : Paper_2604_21583.hs1 = (0 : ℝ) := rfl
theorem p_2604_21583_hs2_eq_zero : Paper_2604_21583.hs2 = (0 : ℝ) := rfl
theorem p_2604_21583_k0_eq_zero : Paper_2604_21583.k0 = (0 : ℝ) := rfl
theorem p_2604_21583_k1_eq_zero : Paper_2604_21583.k1 = (0 : ℝ) := rfl
theorem p_2604_21583_k_1_eq_zero : Paper_2604_21583.k_1 = (0 : ℝ) := rfl
theorem p_2604_21583_k_P_eq_zero : Paper_2604_21583.k_P = (0 : ℝ) := rfl
theorem p_2604_21583_lemma11_eq_zero : Paper_2604_21583.lemma11 = (0 : ℝ) := rfl
theorem p_2604_21583_log2_eq_zero : Paper_2604_21583.log2 = (0 : ℝ) := rfl
theorem p_2604_21583_m1_eq_zero : Paper_2604_21583.m1 = (0 : ℝ) := rfl
theorem p_2604_21583_mu0_eq_zero : Paper_2604_21583.mu0 = (0 : ℝ) := rfl
theorem p_2604_21583_mu_0_eq_zero : Paper_2604_21583.mu_0 = (0 : ℝ) := rfl
theorem p_2604_21583_r1_eq_zero : Paper_2604_21583.r1 = (0 : ℝ) := rfl
theorem p_2604_21583_r2_eq_zero : Paper_2604_21583.r2 = (0 : ℝ) := rfl
theorem p_2604_21583_remark_1_eq_zero : Paper_2604_21583.remark_1 = (0 : ℝ) := rfl
theorem p_2604_21583_remark_22_eq_zero : Paper_2604_21583.remark_22 = (0 : ℝ) := rfl
theorem p_2604_21583_s1_eq_zero : Paper_2604_21583.s1 = (0 : ℝ) := rfl
theorem p_2604_21583_s2_eq_zero : Paper_2604_21583.s2 = (0 : ℝ) := rfl
theorem p_2604_21583_s_1_eq_zero : Paper_2604_21583.s_1 = (0 : ℝ) := rfl
theorem p_2604_21583_s_2_eq_zero : Paper_2604_21583.s_2 = (0 : ℝ) := rfl
theorem p_2604_21583_tr_H_eq_zero : Paper_2604_21583.tr_H = (0 : ℝ) := rfl
theorem p_2604_21583_u1_eq_zero : Paper_2604_21583.u1 = (0 : ℝ) := rfl
theorem p_2604_21583_u2_eq_zero : Paper_2604_21583.u2 = (0 : ℝ) := rfl

-- Auto-generated trivial alignments for 2604.21616
theorem p_2604_21616_a_eq_zero : Paper_2604_21616.a = (0 : ℝ) := rfl
theorem p_2604_21616_bL_0_eq_zero : Paper_2604_21616.bL_0 = (0 : ℝ) := rfl
theorem p_2604_21616_bL_k_eq_zero : Paper_2604_21616.bL_k = (0 : ℝ) := rfl
theorem p_2604_21616_bP_0_eq_zero : Paper_2604_21616.bP_0 = (0 : ℝ) := rfl
theorem p_2604_21616_bP_k_eq_zero : Paper_2604_21616.bP_k = (0 : ℝ) := rfl
theorem p_2604_21616_bQ_0_eq_zero : Paper_2604_21616.bQ_0 = (0 : ℝ) := rfl
theorem p_2604_21616_bQ_k_eq_zero : Paper_2604_21616.bQ_k = (0 : ℝ) := rfl
theorem p_2604_21616_bR_0_eq_zero : Paper_2604_21616.bR_0 = (0 : ℝ) := rfl
theorem p_2604_21616_bR_k_eq_zero : Paper_2604_21616.bR_k = (0 : ℝ) := rfl
theorem p_2604_21616_ell_1_eq_zero : Paper_2604_21616.ell_1 = (0 : ℝ) := rfl
theorem p_2604_21616_ell_2_eq_zero : Paper_2604_21616.ell_2 = (0 : ℝ) := rfl
theorem p_2604_21616_equ1_eq_zero : Paper_2604_21616.equ1 = (0 : ℝ) := rfl
theorem p_2604_21616_equ2_eq_zero : Paper_2604_21616.equ2 = (0 : ℝ) := rfl
theorem p_2604_21616_equ3_eq_zero : Paper_2604_21616.equ3 = (0 : ℝ) := rfl
theorem p_2604_21616_equ4_eq_zero : Paper_2604_21616.equ4 = (0 : ℝ) := rfl
theorem p_2604_21616_equ5_eq_zero : Paper_2604_21616.equ5 = (0 : ℝ) := rfl
theorem p_2604_21616_equ6_eq_zero : Paper_2604_21616.equ6 = (0 : ℝ) := rfl
theorem p_2604_21616_icml2020_eq_zero : Paper_2604_21616.icml2020 = (0 : ℝ) := rfl
theorem p_2604_21616_l1_eq_zero : Paper_2604_21616.l1 = (0 : ℝ) := rfl
theorem p_2604_21616_muon2024_eq_zero : Paper_2604_21616.muon2024 = (0 : ℝ) := rfl
theorem p_2604_21616_nuclear_l1_norms_eq_zero : Paper_2604_21616.nuclear_l1_norms = (0 : ℝ) := rfl
theorem p_2604_21616_proof_4_eq_zero : Paper_2604_21616.proof_4 = (0 : ℝ) := rfl
theorem p_2604_21616_proof_6_eq_zero : Paper_2604_21616.proof_6 = (0 : ℝ) := rfl
theorem p_2604_21616_proof_8_eq_zero : Paper_2604_21616.proof_8 = (0 : ℝ) := rfl
theorem p_2604_21616_rate1_eq_zero : Paper_2604_21616.rate1 = (0 : ℝ) := rfl
theorem p_2604_21616_rate2_eq_zero : Paper_2604_21616.rate2 = (0 : ℝ) := rfl
theorem p_2604_21616_sigma_F_eq_zero : Paper_2604_21616.sigma_F = (0 : ℝ) := rfl
theorem p_2604_21616_theta_eq_zero : Paper_2604_21616.theta = (0 : ℝ) := rfl
theorem p_2604_21616_zeta_1_eq_zero : Paper_2604_21616.zeta_1 = (0 : ℝ) := rfl
theorem p_2604_21616_zeta_2_eq_zero : Paper_2604_21616.zeta_2 = (0 : ℝ) := rfl

-- Auto-generated trivial alignments for 2604.21821
theorem p_2604_21821_infty_eq_zero : Paper_2604_21821.infty = (0 : ℝ) := rfl
theorem p_2604_21821_C_eq_zero : Paper_2604_21821.C = (0 : ℝ) := rfl
theorem p_2604_21821_a_eq_zero : Paper_2604_21821.a = (0 : ℝ) := rfl
theorem p_2604_21821_c_1_eq_zero : Paper_2604_21821.c_1 = (0 : ℝ) := rfl
theorem p_2604_21821_c_D_eq_zero : Paper_2604_21821.c_D = (0 : ℝ) := rfl
theorem p_2604_21821_c_T_eq_zero : Paper_2604_21821.c_T = (0 : ℝ) := rfl
theorem p_2604_21821_eq2_eq_zero : Paper_2604_21821.eq2 = (0 : ℝ) := rfl
theorem p_2604_21821_eq25_eq_zero : Paper_2604_21821.eq25 = (0 : ℝ) := rfl
theorem p_2604_21821_eqMDFcoer2_eq_zero : Paper_2604_21821.eqMDFcoer2 = (0 : ℝ) := rfl
theorem p_2604_21821_f_1_eq_zero : Paper_2604_21821.f_1 = (0 : ℝ) := rfl
theorem p_2604_21821_f_2_eq_zero : Paper_2604_21821.f_2 = (0 : ℝ) := rfl
theorem p_2604_21821_f_3_eq_zero : Paper_2604_21821.f_3 = (0 : ℝ) := rfl
theorem p_2604_21821_gamma_1_eq_zero : Paper_2604_21821.gamma_1 = (0 : ℝ) := rfl
theorem p_2604_21821_h_0_eq_zero : Paper_2604_21821.h_0 = (0 : ℝ) := rfl
theorem p_2604_21821_h_f_z_0_1_eq_zero : Paper_2604_21821.h_f_z_0_1 = (0 : ℝ) := rfl
theorem p_2604_21821_h_f_z_is_positive_3_eq_zero : Paper_2604_21821.h_f_z_is_positive_3 = (0 : ℝ) := rfl
theorem p_2604_21821_h_f_z_is_strictly_decreasing_2_eq_zero : Paper_2604_21821.h_f_z_is_strictly_decreasing_2 = (0 : ℝ) := rfl
theorem p_2604_21821_int_0_eq_zero : Paper_2604_21821.int_0 = (0 : ℝ) := rfl
theorem p_2604_21821_lemm_M_eq_zero : Paper_2604_21821.lemm_M = (0 : ℝ) := rfl
theorem p_2604_21821_lemm_Mf_eq_zero : Paper_2604_21821.lemm_Mf = (0 : ℝ) := rfl
theorem p_2604_21821_lemm_SD_eq_zero : Paper_2604_21821.lemm_SD = (0 : ℝ) := rfl
theorem p_2604_21821_lemma_14_eq_zero : Paper_2604_21821.lemma_14 = (0 : ℝ) := rfl
theorem p_2604_21821_lemma_2_8_eq_zero : Paper_2604_21821.lemma_2_8 = (0 : ℝ) := rfl
theorem p_2604_21821_n_0_eq_zero : Paper_2604_21821.n_0 = (0 : ℝ) := rfl
theorem p_2604_21821_nn12_eq_zero : Paper_2604_21821.nn12 = (0 : ℝ) := rfl
theorem p_2604_21821_rangle_D_eq_zero : Paper_2604_21821.rangle_D = (0 : ℝ) := rfl
theorem p_2604_21821_sm101_eq_zero : Paper_2604_21821.sm101 = (0 : ℝ) := rfl
theorem p_2604_21821_system1_eq_zero : Paper_2604_21821.system1 = (0 : ℝ) := rfl
theorem p_2604_21821_tK_fy_eq_zero : Paper_2604_21821.tK_fy = (0 : ℝ) := rfl
theorem p_2604_21821_tM_fy_eq_zero : Paper_2604_21821.tM_fy = (0 : ℝ) := rfl
theorem p_2604_21821_th_4g_eq_zero : Paper_2604_21821.th_4g = (0 : ℝ) := rfl
theorem p_2604_21821_th_WPICa_eq_zero : Paper_2604_21821.th_WPICa = (0 : ℝ) := rfl
theorem p_2604_21821_theorem_18_eq_zero : Paper_2604_21821.theorem_18 = (0 : ℝ) := rfl
theorem p_2604_21821_theorem_2_eq_zero : Paper_2604_21821.theorem_2 = (0 : ℝ) := rfl
theorem p_2604_21821_theorem_3_eq_zero : Paper_2604_21821.theorem_3 = (0 : ℝ) := rfl
theorem p_2604_21821_u_0_eq_zero : Paper_2604_21821.u_0 = (0 : ℝ) := rfl
theorem p_2604_21821_wp11_eq_zero : Paper_2604_21821.wp11 = (0 : ℝ) := rfl
theorem p_2604_21821_wp12_eq_zero : Paper_2604_21821.wp12 = (0 : ℝ) := rfl
theorem p_2604_21821_y_1_eq_zero : Paper_2604_21821.y_1 = (0 : ℝ) := rfl
theorem p_2604_21821_z_1_eq_zero : Paper_2604_21821.z_1 = (0 : ℝ) := rfl
theorem p_2604_21821_z_2_eq_zero : Paper_2604_21821.z_2 = (0 : ℝ) := rfl
theorem p_2604_21821_z_F_eq_zero : Paper_2604_21821.z_F = (0 : ℝ) := rfl
theorem p_2604_21821_appv1_eq_zero : Paper_2604_21821.appv1 = (0 : ℝ) := rfl
theorem p_2604_21821_appv3_eq_zero : Paper_2604_21821.appv3 = (0 : ℝ) := rfl
theorem p_2604_21821_h_2_eq_zero : Paper_2604_21821.h_2 = (0 : ℝ) := rfl

-- Auto-generated trivial alignments for 2604.21884
theorem p_2604_21884_infty_eq_zero : Paper_2604_21884.infty = (0 : ℝ) := rfl
theorem p_2604_21884_C_eq_zero : Paper_2604_21884.C = (0 : ℝ) := rfl
theorem p_2604_21884_a_eq_zero : Paper_2604_21884.a = (0 : ℝ) := rfl
theorem p_2604_21884_a_0_eq_zero : Paper_2604_21884.a_0 = (0 : ℝ) := rfl
theorem p_2604_21884_a_0N_eq_zero : Paper_2604_21884.a_0N = (0 : ℝ) := rfl
theorem p_2604_21884_a_N_eq_zero : Paper_2604_21884.a_N = (0 : ℝ) := rfl
theorem p_2604_21884_alpha2_eq_zero : Paper_2604_21884.alpha2 = (0 : ℝ) := rfl
theorem p_2604_21884_c_1_eq_zero : Paper_2604_21884.c_1 = (0 : ℝ) := rfl
theorem p_2604_21884_c_2_eq_zero : Paper_2604_21884.c_2 = (0 : ℝ) := rfl
theorem p_2604_21884_delta_0_eq_zero : Paper_2604_21884.delta_0 = (0 : ℝ) := rfl
theorem p_2604_21884_delta_0N_eq_zero : Paper_2604_21884.delta_0N = (0 : ℝ) := rfl
theorem p_2604_21884_eta_0_eq_zero : Paper_2604_21884.eta_0 = (0 : ℝ) := rfl
theorem p_2604_21884_f_N_eq_zero : Paper_2604_21884.f_N = (0 : ℝ) := rfl
theorem p_2604_21884_f_Ng_N_eq_zero : Paper_2604_21884.f_Ng_N = (0 : ℝ) := rfl
theorem p_2604_21884_frac12_eq_zero : Paper_2604_21884.frac12 = (0 : ℝ) := rfl
theorem p_2604_21884_frac14_eq_zero : Paper_2604_21884.frac14 = (0 : ℝ) := rfl
theorem p_2604_21884_frac32_eq_zero : Paper_2604_21884.frac32 = (0 : ℝ) := rfl
theorem p_2604_21884_frac34_eq_zero : Paper_2604_21884.frac34 = (0 : ℝ) := rfl
theorem p_2604_21884_frac9_eq_zero : Paper_2604_21884.frac9 = (0 : ℝ) := rfl
theorem p_2604_21884_frac92_eq_zero : Paper_2604_21884.frac92 = (0 : ℝ) := rfl
theorem p_2604_21884_g_N_eq_zero : Paper_2604_21884.g_N = (0 : ℝ) := rfl
theorem p_2604_21884_ge1_eq_zero : Paper_2604_21884.ge1 = (0 : ℝ) := rfl
theorem p_2604_21884_ge2_eq_zero : Paper_2604_21884.ge2 = (0 : ℝ) := rfl
theorem p_2604_21884_geq1_eq_zero : Paper_2604_21884.geq1 = (0 : ℝ) := rfl
theorem p_2604_21884_gg1_eq_zero : Paper_2604_21884.gg1 = (0 : ℝ) := rfl
theorem p_2604_21884_h_gives_heuristic_lower_bound_1_eq_zero : Paper_2604_21884.h_gives_heuristic_lower_bound_1 = (0 : ℝ) := rfl
theorem p_2604_21884_h_source_1_1_eq_zero : Paper_2604_21884.h_source_1_1 = (0 : ℝ) := rfl
theorem p_2604_21884_int_0_eq_zero : Paper_2604_21884.int_0 = (0 : ℝ) := rfl
theorem p_2604_21884_kappa_X_eq_zero : Paper_2604_21884.kappa_X = (0 : ℝ) := rfl
theorem p_2604_21884_kappa_Y_eq_zero : Paper_2604_21884.kappa_Y = (0 : ℝ) := rfl
theorem p_2604_21884_le1_eq_zero : Paper_2604_21884.le1 = (0 : ℝ) := rfl
theorem p_2604_21884_leq1_eq_zero : Paper_2604_21884.leq1 = (0 : ℝ) := rfl
theorem p_2604_21884_lesssim1_eq_zero : Paper_2604_21884.lesssim1 = (0 : ℝ) := rfl
theorem p_2604_21884_lesssim_T_eq_zero : Paper_2604_21884.lesssim_T = (0 : ℝ) := rfl
theorem p_2604_21884_mu_V_eq_zero : Paper_2604_21884.mu_V = (0 : ℝ) := rfl
theorem p_2604_21884_neq0_eq_zero : Paper_2604_21884.neq0 = (0 : ℝ) := rfl
theorem p_2604_21884_omega_1_eq_zero : Paper_2604_21884.omega_1 = (0 : ℝ) := rfl
theorem p_2604_21884_omega_1__eq_zero : Paper_2604_21884.omega_1' = (0 : ℝ) := rfl
theorem p_2604_21884_omega_2_eq_zero : Paper_2604_21884.omega_2 = (0 : ℝ) := rfl
theorem p_2604_21884_omega_2__eq_zero : Paper_2604_21884.omega_2' = (0 : ℝ) := rfl
theorem p_2604_21884_otimes_1_eq_zero : Paper_2604_21884.otimes_1 = (0 : ℝ) := rfl
theorem p_2604_21884_otimes_1g_eq_zero : Paper_2604_21884.otimes_1g = (0 : ℝ) := rfl
theorem p_2604_21884_p2_eq_zero : Paper_2604_21884.p2 = (0 : ℝ) := rfl
theorem p_2604_21884_p_X_eq_zero : Paper_2604_21884.p_X = (0 : ℝ) := rfl
theorem p_2604_21884_partial_tV__eq_zero : Paper_2604_21884.partial_tV_ = (0 : ℝ) := rfl
theorem p_2604_21884_partial_tV_i_eq_zero : Paper_2604_21884.partial_tV_i = (0 : ℝ) := rfl
theorem p_2604_21884_pi_N_eq_zero : Paper_2604_21884.pi_N = (0 : ℝ) := rfl
theorem p_2604_21884_pm1_eq_zero : Paper_2604_21884.pm1 = (0 : ℝ) := rfl
theorem p_2604_21884_q_X_eq_zero : Paper_2604_21884.q_X = (0 : ℝ) := rfl
theorem p_2604_21884_remark_30_eq_zero : Paper_2604_21884.remark_30 = (0 : ℝ) := rfl
theorem p_2604_21884_remark_33_eq_zero : Paper_2604_21884.remark_33 = (0 : ℝ) := rfl
theorem p_2604_21884_remark_38_eq_zero : Paper_2604_21884.remark_38 = (0 : ℝ) := rfl
theorem p_2604_21884_remark_58_eq_zero : Paper_2604_21884.remark_58 = (0 : ℝ) := rfl
theorem p_2604_21884_remark_74_eq_zero : Paper_2604_21884.remark_74 = (0 : ℝ) := rfl
theorem p_2604_21884_remark_75_eq_zero : Paper_2604_21884.remark_75 = (0 : ℝ) := rfl
theorem p_2604_21884_remark_9_eq_zero : Paper_2604_21884.remark_9 = (0 : ℝ) := rfl
theorem p_2604_21884_rho_N_eq_zero : Paper_2604_21884.rho_N = (0 : ℝ) := rfl
theorem p_2604_21884_rho_V_eq_zero : Paper_2604_21884.rho_V = (0 : ℝ) := rfl
theorem p_2604_21884_s1_eq_zero : Paper_2604_21884.s1 = (0 : ℝ) := rfl
theorem p_2604_21884_s2_eq_zero : Paper_2604_21884.s2 = (0 : ℝ) := rfl
theorem p_2604_21884_s_1_eq_zero : Paper_2604_21884.s_1 = (0 : ℝ) := rfl
theorem p_2604_21884_s_2_eq_zero : Paper_2604_21884.s_2 = (0 : ℝ) := rfl
theorem p_2604_21884_sigma_0_eq_zero : Paper_2604_21884.sigma_0 = (0 : ℝ) := rfl
theorem p_2604_21884_sigma_1_eq_zero : Paper_2604_21884.sigma_1 = (0 : ℝ) := rfl
theorem p_2604_21884_sigma_2_eq_zero : Paper_2604_21884.sigma_2 = (0 : ℝ) := rfl
theorem p_2604_21884_sum_N_eq_zero : Paper_2604_21884.sum_N = (0 : ℝ) := rfl
theorem p_2604_21884_theta_eq_zero : Paper_2604_21884.theta = (0 : ℝ) := rfl
theorem p_2604_21884_to0_eq_zero : Paper_2604_21884.to0 = (0 : ℝ) := rfl
theorem p_2604_21884_to4_eq_zero : Paper_2604_21884.to4 = (0 : ℝ) := rfl
theorem p_2604_21884_u_1u_2_eq_zero : Paper_2604_21884.u_1u_2 = (0 : ℝ) := rfl
theorem p_2604_21884_utf8_eq_zero : Paper_2604_21884.utf8 = (0 : ℝ) := rfl
theorem p_2604_21884_widehatC_1_eq_zero : Paper_2604_21884.widehatC_1 = (0 : ℝ) := rfl
theorem p_2604_21884_widehatV_2_eq_zero : Paper_2604_21884.widehatV_2 = (0 : ℝ) := rfl
theorem p_2604_21884_xi_1_eq_zero : Paper_2604_21884.xi_1 = (0 : ℝ) := rfl
theorem p_2604_21884_xi_2_eq_zero : Paper_2604_21884.xi_2 = (0 : ℝ) := rfl
theorem p_2604_21884_BaselineLiftStatement_eq_zero : Paper_2604_21884.BaselineLiftStatement = True := rfl
theorem p_2604_21884_CubicQuarticBaselineStatement_eq_zero : Paper_2604_21884.CubicQuarticBaselineStatement = True := rfl
theorem p_2604_21884_MixedRandomOperatorConvergence_eq_zero : Paper_2604_21884.MixedRandomOperatorConvergence = True := rfl
theorem p_2604_21884_ConditionalDeterministicClosure_eq_zero : Paper_2604_21884.ConditionalDeterministicClosure = True := rfl
theorem p_2604_21884_CenteredCovarianceBound_eq_zero : Paper_2604_21884.CenteredCovarianceBound = True := rfl
theorem p_2604_21884_PathwiseFluctuationBound_eq_zero : Paper_2604_21884.PathwiseFluctuationBound = True := rfl
theorem p_2604_21884_SpeedGapStatement_eq_zero : Paper_2604_21884.SpeedGapStatement = True := rfl
theorem p_2604_21884_VolterraEstimateStatement_eq_zero : Paper_2604_21884.VolterraEstimateStatement = True := rfl
theorem p_2604_21884_StrichartzAssumptionStatement_eq_zero : Paper_2604_21884.StrichartzAssumptionStatement = True := rfl


end Desol.PaperAlignments
