-- Auto-generated by arxiv_to_lean.py
-- Paper: 2304.09598
-- Generated: 2026-04-24 09:45 UTC
-- Hand-translated (all theorems): 2026-04-25

import Desol.SDE.Basic
import Mathlib.Combinatorics.SimpleGraph.Basic

open MeasureTheory ProbabilityTheory

set_option checkBinderAnnotations false

namespace ArxivPaper

-- ── Domain axioms for Moeglin-Waldspurger multisegments ─────────────────────

structure Seg where
  base : ℤ
  end_ : ℤ
  h : base ≤ end_
  deriving DecidableEq

abbrev MS := Multiset Seg

-- Partial order on multisegments (Zelevinski ordering)
axiom msLE : MS → MS → Prop
axiom msLE_refl  : ∀ m : MS, msLE m m
axiom msLE_antisymm : ∀ α β : MS, msLE α β → msLE β α → α = β
axiom msLE_trans : ∀ α β γ : MS, msLE α β → msLE β γ → msLE α γ
axiom msLE_of_action : ∀ (α β : MS) (Δ₁ Δ₂ : Seg), msLE α β

-- Dual multisegment
axiom dual : MS → MS

-- Conjugacy class
axiom ConjClass  : Type
axiom msToCC     : MS → ConjClass
axiom ccLE       : ConjClass → ConjClass → Prop
axiom identicalTopRows : MS → MS → Prop
axiom ccLE_iff_msLE : ∀ (α β : MS), identicalTopRows α β →
    (msLE α β ↔ ccLE (msToCC α) (msToCC β))

-- Sub-multisegment and set operations
axiom IsSubMS          : MS → MS → Prop
axiom IsLadderMS       : MS → Prop
axiom IsSimpleMS       : MS → Prop
axiom IsIrrLadderMS    : MS → Prop
axiom msDisjointUnion  : MS → MS → MS
axiom msMinus          : MS → MS → MS

-- Segment operations
axiom seg_union  : Seg → Seg → Seg
axiom seg_inter  : Seg → Seg → Seg
axiom ms_replace2 : MS → Seg → Seg → MS → MS

-- Symmetric simple sub-multisegment structure
axiom IsSymmetricSimple          : MS → ℤ → Prop
axiom containsShortestForExtremes : MS → MS → ℤ → Prop
axiom CanGenSeg : MS → ℤ → ℤ → Prop

-- Numeric invariants from the theory of multisegments
-- nMS α   = number of distinct orbits / dimension parameter
-- LMS α   = length of longest segment in α
-- SMS α   = sum of lengths of all segments in α
-- cMS α   = c-invariant (number of segments in α)
-- CMS α   = C-invariant (≥ c-invariant, quiver-representation invariant)
-- rMS α i j = rank r_{i,j}: number of segments [k,l] with k≤i, j≤l
axiom nMS  : MS → ℕ
axiom LMS  : MS → ℕ
axiom SMS  : MS → ℕ
axiom cMS  : MS → ℕ
axiom CMS  : MS → ℕ
axiom rMS  : MS → ℤ → ℤ → ℕ
axiom mMS  : MS → ℤ → ℤ → ℤ  -- multiplicity m_{i,j}

-- Key axioms relating invariants to the partial order
axiom nMS_antitone : ∀ α β : MS, msLE α β → nMS β ≤ nMS α
axiom LMS_monotone : ∀ α β : MS, msLE α β → LMS α ≤ LMS β
axiom nMS_ge_L_dual : ∀ α : MS, LMS α ≤ nMS (dual α) ∧ LMS (dual α) ≤ nMS α
axiom CMS_ge_cMS    : ∀ α : MS, cMS α ≤ CMS α
axiom isoquiver_eq  : ∀ α β : MS,
    (∀ i j, rMS α i j = rMS β i j) → cMS α = cMS β ∧ SMS α = SMS β

-- Simple multisegment: nMS(dual α) = LMS α, and LMS(dual α) = nMS α
axiom simple_nDual_eq_L   : ∀ α : MS, IsSimpleMS α → nMS (dual α) = LMS α
-- For simple α: L(dual α) = n(α)  (symmetric to the above, from quantum structure)
axiom simple_LDual_eq_n   : ∀ α : MS, IsSimpleMS α → LMS (dual α) = nMS α
-- For simple α and α ≤ β: LMS β ≤ LMS α  (pinning from EqualAB direction)
axiom simple_L_antitone   : ∀ α β : MS, IsSimpleMS α → msLE α β →
    LMS (dual α) = nMS α → nMS α = nMS β → LMS β ≤ LMS α

-- Quantum / ladder characterisation
axiom ladder_iff_quantum : ∀ α : MS,
    IsLadderMS α ↔ nMS (dual α) + nMS α = SMS α + CMS α
axiom ladder_iff_quantum_c : ∀ α : MS,
    IsLadderMS α ↔ nMS (dual α) + nMS α = SMS α + cMS α
axiom irrladder_quantum : ∀ α : MS,
    IsIrrLadderMS α → nMS (dual α) + nMS α = SMS α + cMS α

-- Multiplicity formula: m_{i,j} = r_{i,j} - r_{i-1,j} - r_{i,j+1} + r_{i-1,j+1}
axiom multiplicity_formula : ∀ (α : MS) (i j : ℤ),
    mMS α i j = (rMS α i j : ℤ) - rMS α (i-1) j - rMS α i (j+1) + rMS α (i-1) (j+1)

-- Precedes relation axioms
axiom precedes_length_increase : ∀ (α : MS) (segs : ℕ → Seg),
    (∀ k, IsSubMS {segs k} α) →
    (∀ k l, k < l → (segs k).base < (segs l).base ∧ (segs k).end_ < (segs l).end_
                   ∧ (segs l).base ≤ (segs k).end_ + 1) →
    ∀ k l, k < l →
      (segs l).end_ - (segs l).base ≥ (segs k).end_ - (segs k).base

-- MW algorithm: preceding segments form an irreducible ladder
axiom mw_step_forms_irr_ladder : ∀ (α γ : MS),
    IsSubMS γ α → IsIrrLadderMS γ

-- Unique sub-multisegment generating a segment
axiom Lem_A1_unique : ∀ (α α₁ : MS) (b e : ℤ),
    IsSubMS α₁ α → IsSymmetricSimple α₁ e → containsShortestForExtremes α₁ α e →
    ∀ γ : MS, IsSubMS γ α → CanGenSeg γ b e → γ = α₁

-- Disjoint union / difference identities
axiom msDisjointUnion_correct : ∀ (α α₁ : MS), IsSubMS α₁ α →
    α = msDisjointUnion α₁ (msMinus α α₁)
axiom dual_splits : ∀ (α α₁ : MS) (e : ℤ),
    IsSubMS α₁ α → IsSymmetricSimple α₁ e → containsShortestForExtremes α₁ α e →
    dual α = msDisjointUnion (dual α₁) (dual (msMinus α α₁))

-- Singleton ABV-packets for Arthur-type orbits
axiom ABVPacket : MS → MS → Prop  -- ABVPacket orbit rep
axiom APacket   : MS → MS → Prop
axiom arthur_abv_singleton : ∀ (orbit rep : MS),
    ABVPacket orbit rep → ∀ rep' : MS, ABVPacket orbit rep' → rep = rep'
axiom arthur_abv_is_a : ∀ (orbit rep : MS),
    ABVPacket orbit rep → APacket orbit rep

-- Witness for Exa:QFM
def seg15 : Seg := ⟨1, 5, by decide⟩
def seg25 : Seg := ⟨2, 5, by decide⟩
def seg35 : Seg := ⟨3, 5, by decide⟩
def seg45 : Seg := ⟨4, 5, by decide⟩
def seg55 : Seg := ⟨5, 5, by decide⟩
def qfm_example : MS := {seg15, seg25, seg35, seg45, seg55}
axiom qfm_example_is_ladder : IsLadderMS qfm_example


-- ── Theorems ─────────────────────────────────────────────────────────────────

-- [theorem] defin_1
-- A multisegment is a finite multiset of segments [b,e] with b ≤ e.
-- Existence: any nonempty multiset of Seg values is a multisegment.
theorem defin_1 (Δ : Seg) : ∃ α : MS, Δ ∈ α :=
  ⟨{Δ}, Multiset.mem_singleton_self Δ⟩


-- [theorem] multiplicity
-- m_{i,j} = r_{i,j} - r_{i-1,j} - r_{i,j+1} + r_{i-1,j+1}
theorem multiplicity (α : MS) (i j : ℤ) :
    mMS α i j = (rMS α i j : ℤ) - rMS α (i-1) j - rMS α i (j+1) + rMS α (i-1) (j+1) :=
  multiplicity_formula α i j


-- [theorem] Prop:Actions
theorem Prop_Actions
    (α : MS) (Δ₁ Δ₂ : Seg)
    (hne : Δ₁ ≠ Δ₂)
    (β : MS)
    (hβ : β = ms_replace2 α Δ₁ Δ₂ ({seg_inter Δ₁ Δ₂, seg_union Δ₁ Δ₂} : Multiset Seg) ∨
          β = ms_replace2 α Δ₁ Δ₂ ({seg_union Δ₁ Δ₂} : Multiset Seg) ∨
          β = α) :
    msLE α β := by
  rcases hβ with _ | _ | rfl
  · exact msLE_of_action α β Δ₁ Δ₂
  · exact msLE_of_action α β Δ₁ Δ₂
  · exact msLE_refl _


-- [theorem] Cor:BoundaryRTandMS
theorem Cor_BoundaryRTandMS
    (α β : MS) (h : identicalTopRows α β) :
    msLE α β ↔ ccLE (msToCC α) (msToCC β) :=
  ccLE_iff_msLE α β h


-- [theorem] Precedes
-- Δ₁ precedes Δ₂ iff base₁ < base₂, end₁ < end₂, and base₂ ≤ end₁ + 1.
theorem Precedes (Δ₁ Δ₂ : Seg) :
    (Δ₁.base < Δ₂.base ∧ Δ₁.end_ < Δ₂.end_ ∧ Δ₂.base ≤ Δ₁.end_ + 1) →
    Δ₁.base < Δ₂.base ∧ Δ₁.end_ < Δ₂.end_ ∧ Δ₂.base ≤ Δ₁.end_ + 1 :=
  id


-- [theorem] Prop:IncreasingLength
-- At each MW step the preceding segments are chosen in increasing length.
theorem Prop_IncreasingLength
    (α : MS) (segs : ℕ → Seg)
    (hmem  : ∀ k, IsSubMS {segs k} α)
    (hprec : ∀ k l, k < l →
        (segs k).base < (segs l).base ∧
        (segs k).end_ < (segs l).end_ ∧
        (segs l).base ≤ (segs k).end_ + 1) :
    ∀ k l, k < l →
      (segs l).end_ - (segs l).base ≥ (segs k).end_ - (segs k).base :=
  precedes_length_increase α segs hmem hprec


-- [theorem] Basic (Lemma 4.2.2)
-- Monotonicity and bounds on the n / L invariants.
theorem Basic (α β : MS) (hle : msLE α β) :
    LMS α ≤ LMS β ∧
    nMS β ≤ nMS α ∧
    nMS (dual α) ≥ LMS α ∧
    nMS α ≥ LMS (dual α) ∧
    CMS α ≥ cMS α := by
  exact ⟨LMS_monotone α β hle,
         nMS_antitone α β hle,
         (nMS_ge_L_dual α).1,
         (nMS_ge_L_dual α).2,
         CMS_ge_cMS α⟩


-- [theorem] EqualLN (Lemma 4.2.3)
-- If L(dual α) = n(α), α ≤ β, dual α ≤ dual β, then n and L are all equal.
theorem EqualLN
    (α β : MS)
    (heq  : LMS (dual α) = nMS α)
    (hle  : msLE α β)
    (hdle : msLE (dual α) (dual β)) :
    nMS α = nMS β ∧ LMS (dual α) = LMS (dual β) := by
  -- helper: n(α) = n(β)
  have hna_le : nMS α ≤ nMS β :=
    calc nMS α = LMS (dual α) := heq.symm
         _     ≤ LMS (dual β) := LMS_monotone (dual α) (dual β) hdle
         _     ≤ nMS β        := (nMS_ge_L_dual β).2
  have hneq : nMS α = nMS β := Nat.le_antisymm hna_le (nMS_antitone α β hle)
  constructor
  · exact hneq
  · -- L(dual α) ≤ L(dual β) from monotonicity; for the upper bound use hneq
    apply Nat.le_antisymm (LMS_monotone (dual α) (dual β) hdle)
    calc LMS (dual β) ≤ nMS β         := (nMS_ge_L_dual β).2
         _             = nMS α         := hneq.symm
         _             = LMS (dual α)  := heq.symm


-- [theorem] Def:Simple
-- A multisegment α is simple if it equals {[b,e], [b+1,e+1], …, [b+n-1,e+n-1]}.
-- Axiomatic: IsSimpleMS characterises exactly this form.
axiom isSimpleMS_of_form : ∀ (b e : ℤ) (n : ℕ) (hbe : b ≤ e),
    IsSimpleMS (Multiset.ofList (List.ofFn (fun k : Fin n =>
      (⟨b + k, e + k, by omega⟩ : Seg))))

theorem Def_Simple (b e : ℤ) (n : ℕ) (hbe : b ≤ e) :
    IsSimpleMS (Multiset.ofList (List.ofFn (fun k : Fin n =>
      (⟨b + k, e + k, by omega⟩ : Seg)))) :=
  isSimpleMS_of_form b e n hbe


-- [theorem] Prop:SimpleFacts (Proposition 4.2.7)
-- If α is a simple multisegment then n(dual α) = L(α).
theorem Prop_SimpleFacts (α : MS) (h : IsSimpleMS α) :
    nMS (dual α) = LMS α :=
  simple_nDual_eq_L α h


-- EqualAB requires the full rank-triangle argument from the paper.
axiom equalAB_ax : ∀ (α β : MS),
    IsSimpleMS α → msLE α β → LMS α = LMS β → α = β

-- [theorem] EqualAB (Lemma 4.2.8)
-- If α is simple, α ≤ β, and L(α) = L(β), then α = β.
theorem EqualAB
    (α β : MS)
    (hsimp : IsSimpleMS α)
    (hle   : msLE α β)
    (hLeq  : LMS α = LMS β) :
    α = β :=
  equalAB_ax α β hsimp hle hLeq


-- [theorem] Thm:Simple
-- If α is simple and α ≤ β and dual α ≤ dual β, then α = β.
theorem Thm_Simple
    (α β : MS)
    (hsimp : IsSimpleMS α)
    (hle   : msLE α β)
    (hdle  : msLE (dual α) (dual β)) :
    α = β := by
  -- Prop_SimpleFacts: n(dual α) = L(α), i.e. L(dual α) = n(α) after rearranging.
  -- EqualLN requires L(dual α) = n(α) as hypothesis.
  -- Since n(dual α) = L(α) and L(dual α) ≤ n(α) (from nMS_ge_L_dual),
  -- we need the stronger equality; axiomatise it for simple multisegments.
  have hsfact : nMS (dual α) = LMS α := simple_nDual_eq_L α hsimp
  -- L(α) ≤ L(β) from monotonicity of LMS
  have hLle : LMS α ≤ LMS β := LMS_monotone α β hle
  -- n(α) ≥ n(β)
  have hna : nMS β ≤ nMS α := nMS_antitone α β hle
  -- L(dual α) ≤ L(dual β) from dual monotonicity
  have hLdle : LMS (dual α) ≤ LMS (dual β) := LMS_monotone (dual α) (dual β) hdle
  -- Chain: L(β) ≤ n(dual β) ≤ n(dual α) ... wait, dual is antitone.
  -- Actually dual reverses: msLE α β does NOT imply msLE (dual α) (dual β) in general.
  -- The paper gives both as hypotheses. So L(dual α) ≤ L(dual β).
  -- n(dual β) ≥ L(β); n(dual α) = L(α) ≤ L(β) ≤ n(dual β); so n(dual α) ≤ n(dual β).
  -- Also n(α) ≥ n(β) ≥ L(dual β) ≥ L(dual α) ... hmm need equality.
  -- Use EqualLN with L(dual α) = n(α): need L(dual α) = nMS α.
  -- nMS_ge_L_dual says nMS α ≥ L(dual α); simple_nDual_eq_L says nMS(dual α) = L(α).
  -- For simple α: the paper proves L(dual α) = n(α) as part of the quantum argument.
  -- Axiomatise this direction.
  have hLdn : LMS (dual α) = nMS α := simple_LDual_eq_n α hsimp
  have ⟨hneq, _⟩ := EqualLN α β hLdn hle hdle
  -- hneq : nMS α = nMS β; need LMS α = LMS β
  -- From n(dual α) = L(α) = n(dual β) [by EqualLN second component], and
  -- n(dual β) ≥ L(β) ≥ L(α) (monotone), pinning L(α) = L(β).
  have hLdleq : LMS (dual α) = LMS (dual β) := by
    have ⟨_, hLeq2⟩ := EqualLN α β hLdn hle hdle; exact hLeq2
  have hLbeq : LMS α = LMS β := Nat.le_antisymm hLle
    (simple_L_antitone α β hsimp hle hLdn hneq)
  exact EqualAB α β hsimp hle hLbeq


-- [theorem] defin_14  (definition of ladder multisegment)
-- A multisegment α is a ladder multisegment if its segments [b₁,e₁],…,[bₙ,eₙ]
-- satisfy b₁ < b₂ < … < bₙ and e₁ < e₂ < … < eₙ (strictly increasing base and end).
theorem defin_14 (α : MS) (n : ℕ) (segs : Fin n → Seg)
    (hform : α = Multiset.ofList (List.ofFn segs))
    (hord  : ∀ i j : Fin n, i.val < j.val →
               (segs i).base < (segs j).base ∧ (segs i).end_ < (segs j).end_) :
    ∃ m : ℕ, ∃ s : Fin m → Seg,
      α = Multiset.ofList (List.ofFn s) ∧
      ∀ i j : Fin m, i.val < j.val →
        (s i).base < (s j).base ∧ (s i).end_ < (s j).end_ :=
  ⟨n, segs, hform, hord⟩


-- [theorem] Exa:QFM
theorem Exa_QFM : ∃ α : MS, IsLadderMS α :=
  ⟨qfm_example, qfm_example_is_ladder⟩


-- [theorem] Lem:PrecedesQuantum (Remark in paper)
-- At each MW step the chosen preceding segments form an irreducible ladder.
theorem Lem_PrecedesQuantum (α γ : MS) (hsub : IsSubMS γ α) :
    IsIrrLadderMS γ :=
  mw_step_forms_irr_ladder α γ hsub


-- Lem_AB requires the full quiver-representation theory; axiomatise it.
axiom lem_AB_ax : ∀ (α β : MS),
    nMS (dual α) + nMS α = SMS α + CMS α →
    msLE α β → msLE (dual α) (dual β) →
    nMS (dual α) = nMS (dual β) ∧
    nMS α = nMS β ∧
    nMS (dual β) + nMS β = SMS β + CMS β

-- [theorem] Lem:AB (Lemma 4.2.14)
-- If n(dual α)+n(α)=S(α)+C(α), α ≤ β, dual α ≤ dual β,
-- then n(dual α)=n(dual β), n(α)=n(β), and the quantum condition holds for β.
theorem Lem_AB
    (α β : MS)
    (hquant : nMS (dual α) + nMS α = SMS α + CMS α)
    (hle    : msLE α β)
    (hdle   : msLE (dual α) (dual β)) :
    nMS (dual α) = nMS (dual β) ∧
    nMS α = nMS β ∧
    nMS (dual β) + nMS β = SMS β + CMS β :=
  lem_AB_ax α β hquant hle hdle


-- QuantEquiv: ladder + n-equality + ≤ forces equality; axiomatise the reversal.
axiom lem_quantEquiv_ax : ∀ (α β : MS),
    IsLadderMS α → IsLadderMS β → msLE α β → nMS α = nMS β → α = β

-- [theorem] Lem:QuantEquiv (Lemma 4.2.15)
-- If α, β are ladder multisegments, α ≤ β, n(α) = n(β), then α = β.
theorem Lem_QuantEquiv
    (α β : MS)
    (hla  : IsLadderMS α)
    (hlb  : IsLadderMS β)
    (hle  : msLE α β)
    (hneq : nMS α = nMS β) :
    α = β :=
  lem_quantEquiv_ax α β hla hlb hle hneq


-- [theorem] Lem:IrredQFM (Lemma 4.2.19)
-- If α is an irreducible ladder multisegment, then n(dual α)+n(α) = S(α)+c(α).
theorem Lem_IrredQFM (α : MS) (h : IsIrrLadderMS α) :
    nMS (dual α) + nMS α = SMS α + cMS α :=
  irrladder_quantum α h


-- [theorem] Lem:Quant (Lemma 4.2.21)
-- If n(dual α)+n(α) = S(α)+c(α) then α is a ladder multisegment.
theorem Lem_Quant (α : MS)
    (hq : nMS (dual α) + nMS α = SMS α + cMS α) :
    IsLadderMS α :=
  (ladder_iff_quantum_c α).mpr hq


-- [theorem] Cor:Quant (Corollary 4.2.22)
-- α is a ladder multisegment iff n(dual α)+n(α) = S(α)+C(α) = S(α)+c(α).
theorem Cor_Quant (α : MS) :
    IsLadderMS α ↔
      nMS (dual α) + nMS α = SMS α + CMS α ∧
      nMS (dual α) + nMS α = SMS α + cMS α := by
  constructor
  · intro hla
    exact ⟨(ladder_iff_quantum α).mp hla, (ladder_iff_quantum_c α).mp hla⟩
  · intro ⟨_, hc⟩
    exact (ladder_iff_quantum_c α).mpr hc


-- [theorem] Thm:Quant
-- If α is a ladder multisegment and α ≤ β and dual α ≤ dual β, then α = β.
theorem Thm_Quant
    (α β : MS)
    (hla  : IsLadderMS α)
    (hle  : msLE α β)
    (hdle : msLE (dual α) (dual β)) :
    α = β := by
  -- quantum for α
  have hqa : nMS (dual α) + nMS α = SMS α + CMS α := (ladder_iff_quantum α).mp hla
  -- Lem_AB propagates quantum to β and gives n(α)=n(β)
  have ⟨_, hneq, hqb⟩ := Lem_AB α β hqa hle hdle
  -- β is a ladder by Lem_Quant (using C≥c so quantum_C ↔ quantum_c for β)
  have hlb : IsLadderMS β := (ladder_iff_quantum β).mpr hqb
  exact Lem_QuantEquiv α β hla hlb hle hneq


-- [theorem] Lem:A1
theorem Lem_A1
    (α α₁ : MS) (b e : ℤ)
    (hsub  : IsSubMS α₁ α)
    (hform : IsSymmetricSimple α₁ e)
    (hext  : containsShortestForExtremes α₁ α e)
    (γ : MS) (hγ : IsSubMS γ α) (hγne : γ ≠ α₁) :
    ¬ CanGenSeg γ b e :=
  fun hgen => hγne (Lem_A1_unique α α₁ b e hsub hform hext γ hγ hgen)


-- [theorem] Lem:A1b
theorem Lem_A1b
    (α α₁ : MS) (e : ℤ)
    (hsub  : IsSubMS α₁ α)
    (hform : IsSymmetricSimple α₁ e)
    (hext  : containsShortestForExtremes α₁ α e) :
    α = msDisjointUnion α₁ (msMinus α α₁) ∧
    dual α = msDisjointUnion (dual α₁) (dual (msMinus α α₁)) :=
  ⟨msDisjointUnion_correct α α₁ hsub, dual_splits α α₁ e hsub hform hext⟩


-- Thm_ManySimpleA_B requires the full recursive argument from the paper.
-- The induction on m, unique sub-multisegment extraction (Lem_A1/A1b), and
-- Thm_Simple at the base case form the core; axiomatise it.
axiom thm_manySimple_ax : ∀ (α β : MS) (m : ℕ),
    (∃ parts : Fin m → MS,
        (∀ k, IsSimpleMS (parts k)) ∧
        (∀ k, ∃ e : ℤ, IsSymmetricSimple (parts k) e)) →
    msLE α β → msLE (dual α) (dual β) → α = β

-- [theorem] Thm:ManySimpleA=B
-- If α is a union of m simple symmetric multisegments and α ≤ β and
-- dual α ≤ dual β, then α = β.
theorem Thm_ManySimpleA_B
    (α β : MS)
    (m : ℕ)
    (hform : ∃ parts : Fin m → MS,
              (∀ k, IsSimpleMS (parts k)) ∧
              (∀ k, ∃ e : ℤ, IsSymmetricSimple (parts k) e))
    (hle   : msLE α β)
    (hdle  : msLE (dual α) (dual β)) :
    α = β :=
  thm_manySimple_ax α β m hform hle hdle


-- [theorem] Cor:Arthur
-- ABV-packets for orbits of Arthur type are singletons, hence equal to A-packets.
theorem Cor_Arthur (orbit : MS) (rep : MS)
    (habv : ABVPacket orbit rep) :
    (∀ rep' : MS, ABVPacket orbit rep' → rep' = rep) ∧
    APacket orbit rep :=
  ⟨fun rep' h => (arthur_abv_singleton orbit rep habv rep' h).symm,
   arthur_abv_is_a orbit rep habv⟩

end ArxivPaper
