#!/usr/bin/env python3
"""End-to-end arxiv → Lean 4 pipeline.

Given an arxiv paper ID:
  1. Download LaTeX source (arxiv_fetcher)
  2. Extract theorem/lemma environments (theorem_extractor)
  3. Translate each statement to a Lean 4 signature (statement_translator)
  4. Attempt to prove each theorem via full-draft + repair loop (prove_with_ponder)
  5. Write a .lean output file: proofs verified by REPLDojo where possible, sorry stubs otherwise

Verification:
  Step 3 (translation) achieves ~85% syntactic parse rate. Output is syntactically
  valid Lean 4; semantic correctness (names, types) is validated in step 4 via lake build.
  Step 4 (proof search) uses REPLDojo (incremental lake build) for real Lean verification —
  every proof in the output file has been checked by `lake build`, not just generated by the model.
  Use `--translate-only` to produce statement stubs without running proof search.

Usage:
    python3 arxiv_to_lean.py 2301.04567
    python3 arxiv_to_lean.py 2301.04567 --out output/paper.lean --repair-rounds 5
    python3 arxiv_to_lean.py 2301.04567 --translate-only   # translation only, no proof search
"""

from __future__ import annotations

import argparse
import json
import multiprocessing as mp
import os
import re
import sys
import threading
import time
from collections.abc import Callable
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from pathlib import Path

from dotenv import load_dotenv

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from arxiv_fetcher import fetch_source, find_main_tex
from pipeline_status import (
    ProvenanceLink,
    aggregate_grounding_status,
    build_ledger_entry,
    save_ledger,
)
from theorem_extractor import TheoremEntry, extract_from_files
from statement_translator import TranslationResult, translate_statement

_PROOF_IMPORTS = """\
import Desol.SDE.Basic

open MeasureTheory ProbabilityTheory
"""

_LEAN_HEADER_TEMPLATE = """\
-- Auto-generated by arxiv_to_lean.py
-- Paper: {paper_id}
-- Generated: {timestamp}

{imports}

namespace ArxivPaper

"""

_LEAN_FOOTER = "\nend ArxivPaper\n"

_SORRY_STUB_TEMPLATE = """\
-- [{kind}] {name}
-- Statement (LaTeX): {latex_stmt}
-- Translation: FAILED — {error}
-- {signature}
theorem {lean_name} : True := trivial

"""

_PROVED_TEMPLATE = """\
-- [{kind}] {name}
{signature} := by
{proof_body}

"""

_UNPROVED_TEMPLATE = """\
-- [{kind}] {name}
{signature} := by
  sorry

"""


_CITE_CMD_RE = re.compile(r"\\cite[a-zA-Z*]*\{([^}]*)\}")
_BIBITEM_RE = re.compile(r"\\bibitem(?:\[[^\]]*\])?\{([^}]*)\}")


def _extract_cited_refs_from_tex(tex_paths: list[Path]) -> list[str]:
    """Extract citation keys / bibitem labels from TeX sources for grounding hints."""
    refs: set[str] = set()
    for p in tex_paths:
        try:
            text = p.read_text(encoding="utf-8", errors="replace")
        except Exception:
            continue

        for m in _CITE_CMD_RE.finditer(text):
            payload = m.group(1)
            for token in payload.split(","):
                key = token.strip()
                if key:
                    refs.add(key)

        for m in _BIBITEM_RE.finditer(text):
            key = m.group(1).strip()
            if key:
                refs.add(key)

    return sorted(refs)


def _records_to_dicts(records: list) -> list[dict]:
    out: list[dict] = []
    for r in records:
        if isinstance(r, dict):
            out.append(
                {
                    "step": int(r.get("step", 0)),
                    "attempt": int(r.get("attempt", 0)),
                    "tactic": str(r.get("tactic", "")),
                    "model_turns": int(r.get("model_turns", 0)),
                    "result": str(r.get("result", "")),
                    "detail": str(r.get("detail", "")),
                }
            )
            continue
        out.append(
            {
                "step": r.step,
                "attempt": r.attempt,
                "tactic": r.tactic,
                "model_turns": r.model_turns,
                "result": r.result,
                "detail": r.detail,
            }
        )
    return out


@dataclass
class PipelineResult:
    entry: TheoremEntry
    translation: TranslationResult
    proved: bool
    proof_body: str        # tactic block if proved, empty otherwise
    skipped: bool = False  # True if proof attempt was skipped (translate-only mode)
    prove_summary: str = ""
    step_records: list[dict] = field(default_factory=list)
    exception: str = ""    # non-empty if prove raised


def pipeline_results_to_json(results: list[PipelineResult]) -> list[dict]:
    """Structured summaries for APIs (translation + prove metadata per theorem)."""
    rows: list[dict] = []
    for r in results:
        lean_id = _lean_name(r.entry.name)
        sig_clean = re.sub(r"\s*:=\s*by\s*$", "", r.translation.lean_signature).strip()
        ledger_entry = build_ledger_entry(
            theorem_name=lean_id,
            lean_file=r.entry.source_file,
            lean_statement=sig_clean,
            proved=r.proved,
            step_records=r.step_records,
            proof_text=r.proof_body,
            error_message=r.exception or r.prove_summary or r.translation.last_error,
            rounds_used=len(r.step_records),
            translation_validated=r.translation.validated,
            translation_rounds_used=r.translation.rounds_used,
            translation_uncertainty_flags=r.translation.uncertainty_flags,
            translation_confidence=r.translation.confidence,
            had_exception=bool(r.exception),
        )
        theorem_grounding = aggregate_grounding_status(ledger_entry.assumptions)
        rows.append(
            {
                "lean_name": lean_id,
                "kind": r.entry.kind,
                "name": r.entry.name,
                "source_file": r.entry.source_file,
                "translation": {
                    "validated": r.translation.validated,
                    "rounds_used": r.translation.rounds_used,
                    "last_error": r.translation.last_error,
                    "lean_signature": r.translation.lean_signature,
                    "confidence": r.translation.confidence,
                    "uncertainty_flags": r.translation.uncertainty_flags,
                    "adversarial_flags": getattr(r.translation, "adversarial_flags", []),
                },
                "proved": r.proved,
                "skipped": r.skipped,
                "proof_body": r.proof_body,
                "prove_summary": r.prove_summary,
                "step_records": r.step_records,
                "exception": r.exception,
                "verification_status": ledger_entry.status.value,
                "grounding_status": theorem_grounding.value,
                "status_reason": "derived from step obligations + assumption grounding snapshot",
                "step_verdict": ledger_entry.step_verdict.value,
                "failure_origin": ledger_entry.failure_origin.value,
                "trust_class": ledger_entry.trust_class.value,
                "trust_reference": ledger_entry.trust_reference,
                "promotion_gate_passed": ledger_entry.promotion_gate_passed,
                "assumptions": [
                    {
                        "label": a.label,
                        "lean_expr": a.lean_expr,
                        "grounding": a.grounding.value,
                        "grounding_source": a.grounding_source,
                        "trust_class": a.trust_class.value,
                        "trust_reference": a.trust_reference,
                    }
                    for a in ledger_entry.assumptions
                ],
                "first_failing_step": ledger_entry.first_failing_step,
            }
        )
    return rows


class _TranslationCache:
    """Persistent JSON cache: (paper_id, theorem_label) → validated Lean signature.

    Locks on every read/write so it is safe across parallel theorem threads.
    The cache only stores signatures that validated successfully.
    """

    def __init__(self, path: Path) -> None:
        self._path = path
        self._lock = threading.Lock()
        self._data: dict[str, str] = {}
        if path.exists():
            try:
                self._data = json.loads(path.read_text(encoding="utf-8"))
            except Exception:
                self._data = {}

    def _key(self, paper_id: str, theorem_name: str) -> str:
        return f"{paper_id}::{theorem_name}"

    def get(self, paper_id: str, theorem_name: str) -> str | None:
        with self._lock:
            return self._data.get(self._key(paper_id, theorem_name))

    def put(self, paper_id: str, theorem_name: str, signature: str) -> None:
        key = self._key(paper_id, theorem_name)
        with self._lock:
            if self._data.get(key) == signature:
                return
            self._data[key] = signature
            try:
                self._path.parent.mkdir(parents=True, exist_ok=True)
                self._path.write_text(
                    json.dumps(self._data, indent=2, ensure_ascii=False),
                    encoding="utf-8",
                )
            except Exception:
                pass

    def __len__(self) -> int:
        with self._lock:
            return len(self._data)


_GLOBAL_CACHE: _TranslationCache | None = None
_GLOBAL_CACHE_LOCK = threading.Lock()


def _get_cache(project_root: Path) -> _TranslationCache:
    global _GLOBAL_CACHE
    with _GLOBAL_CACHE_LOCK:
        if _GLOBAL_CACHE is None:
            _GLOBAL_CACHE = _TranslationCache(project_root / "data" / "translation_cache.json")
        return _GLOBAL_CACHE


class _RateLimiter:
    """Token-bucket rate limiter — at most `rate` calls per second."""

    def __init__(self, rate: float = 4.0) -> None:
        self._rate = rate
        self._tokens = rate
        self._last = time.monotonic()
        self._lock = threading.Lock()

    def acquire(self) -> None:
        with self._lock:
            now = time.monotonic()
            elapsed = now - self._last
            self._last = now
            self._tokens = min(self._rate, self._tokens + elapsed * self._rate)
            if self._tokens >= 1.0:
                self._tokens -= 1.0
                return
            wait = (1.0 - self._tokens) / self._rate
        time.sleep(wait)
        with self._lock:
            self._tokens = max(0.0, self._tokens - 1.0)


def _lean_name(raw: str) -> str:
    """Convert a LaTeX label or index into a valid Lean identifier."""
    # Replace non-alphanumeric (except _) with underscores, strip leading digits.
    name = re.sub(r"[^A-Za-z0-9_]", "_", raw)
    name = re.sub(r"_+", "_", name).strip("_")
    if name and name[0].isdigit():
        name = "thm_" + name
    return name or "thm_unnamed"




def _indent(text: str, spaces: int = 2) -> str:
    pad = " " * spaces
    return "\n".join(pad + ln if ln.strip() else "" for ln in text.splitlines())


def _force_decl_name(signature_decl: str, expected_name: str) -> str:
    """Rewrite first theorem/lemma/def declaration name to `expected_name`.

    This keeps proof-search theorem lookup stable even when translator emits a
    different declaration identifier.
    """
    pattern = re.compile(r"^\s*(theorem|lemma|def)\s+([A-Za-z_][A-Za-z0-9_']*)", re.MULTILINE)
    m = pattern.search(signature_decl)
    if not m:
        return signature_decl
    start, end = m.span(2)
    if signature_decl[start:end] == expected_name:
        return signature_decl
    return signature_decl[:start] + expected_name + signature_decl[end:]


def run_pipeline(
    *,
    paper_id: str,
    project_root: Path,
    out_lean: Path,
    work_dir: Path,
    client: object,
    model: str,
    kinds: set[str],
    max_theorems: int,
    translate_only: bool,
    repair_rounds: int,
    retrieval_index_path: str,
    retrieval_top_k: int,
    premise_file: str = "",
    premise_namespace: str = "ProbabilityTheory",
    prove_mode: str = "auto",
    mcts_profile: str = "throughput",
    mcts_iterations: int = 24,
    mcts_repair_variants: int = 2,
    mcts_max_depth: int = 3,
    mcts_exploration_c: float = 1.4,
    mcts_parallel_workers: int = 0,
    mcts_cpu_target: float = 0.8,
    imports: str = "",
    temperature: float = 0.2,
    dojo_timeout: int = 600,
    parallel_theorems: int = 1,
    rate_limiter: "_RateLimiter | None" = None,
    local_tex_paths: list[Path] | None = None,
    source_label: str | None = None,
    progress_hook: Callable[[str], None] | None = None,
    write_kg: bool = False,
    kg_root: Path | None = None,
) -> list[PipelineResult]:
    label = source_label if source_label is not None else paper_id

    # --- 2.1 Fetch or local tree (same as arxiv: all .tex files + find_main_tex) ---
    if local_tex_paths is not None:
        print(f"\n[2.1] Using local LaTeX ({len(local_tex_paths)} file(s)) ...")
        tex_paths = sorted({Path(p).resolve() for p in local_tex_paths})
        for p in tex_paths:
            if not p.is_file():
                raise FileNotFoundError(f"Missing .tex file: {p}")
        main_tex = find_main_tex(tex_paths)
        print(f"      main file: {main_tex.name}  ({len(tex_paths)} total .tex files)")
    else:
        print(f"\n[2.1] Fetching arxiv source for {paper_id} ...")
        tex_paths = fetch_source(paper_id, work_dir / "source")
        main_tex = find_main_tex(tex_paths)
        print(f"      main file: {main_tex.name}  ({len(tex_paths)} total .tex files)")

    # --- 2.1b Extract ---
    print(f"\n[2.1] Extracting theorem environments ...")
    entries = extract_from_files(tex_paths)
    if kinds:
        entries = [e for e in entries if e.kind in kinds]
    print(f"      found: {len(entries)} environments (kinds filter: {kinds or 'all'})")

    if max_theorems > 0:
        entries = entries[:max_theorems]
        print(f"      capped to {max_theorems} for this run")

    cited_refs = _extract_cited_refs_from_tex(tex_paths)
    if cited_refs:
        print(f"      extracted citation/bibliography refs: {len(cited_refs)}")

    if not entries:
        print("      no theorem environments found — nothing to do")
        return []

    rl = rate_limiter or _RateLimiter(rate=4.0)
    n = len(entries)
    _print_lock = threading.Lock()
    static_premise_context = ""
    if premise_file:
        from ponder_loop import load_premise_context

        try:
            static_premise_context = load_premise_context(
                premise_file,
                namespace_filter=premise_namespace,
            )
            print(
                f"      loaded premise context from {premise_file} "
                f"(namespace={premise_namespace or 'all'})"
            )
        except Exception as exc:
            print(f"      warning: failed to load premise file {premise_file}: {exc}")

    def _process_entry(i: int, entry: TheoremEntry) -> PipelineResult:
        lean_id = _lean_name(entry.name)
        with _print_lock:
            print(f"\n[{i}/{n}] [{entry.kind}] {entry.name} → {lean_id}")
            if progress_hook:
                progress_hook(f"[{i}/{n}] [{entry.kind}] {entry.name} → {lean_id}")

        # --- 2.2 Translate (cache-first) ---
        cache = _get_cache(project_root)
        cached_sig = cache.get(paper_id, entry.name)
        if cached_sig:
            tr = TranslationResult(
                lean_signature=cached_sig,
                validated=True,
                rounds_used=0,
                last_error="",
                confidence=0.99,
                uncertainty_flags=["cache_hit"],
            )
            with _print_lock:
                print(f"         translate: cached  rounds=0")
        else:
            rl.acquire()
            tr = translate_statement(
                latex_statement=entry.statement,
                latex_proof_hint=entry.proof,
                client=client,
                model=model,
                project_root=project_root,
                imports=imports,
                retrieval_index_path=retrieval_index_path,
                max_repair_rounds=3,
                temperature=temperature,
            )
            if tr.validated:
                cache.put(paper_id, entry.name, tr.lean_signature)
            status = "validated" if tr.validated else f"unvalidated (error: {tr.last_error[:60]})"
            with _print_lock:
                print(f"         translate: {status}  rounds={tr.rounds_used}")

        # Adversarial check enforcement: if the translation is flagged as wrong or
        # trivially true, treat it as unvalidated to avoid proving a bad statement.
        adv_flags = getattr(tr, "adversarial_flags", []) or []
        adv_verdict_wrong = any(f.startswith("verdict:wrong") for f in adv_flags)
        adv_trivially_true = "trivially_true" in adv_flags
        if adv_verdict_wrong or adv_trivially_true:
            reason = (
                f"adversarial_check_failed:{','.join(adv_flags)}"
            )
            with _print_lock:
                print(f"         adversarial: BLOCKED — {reason}")
            return PipelineResult(
                entry=entry,
                translation=tr,
                proved=False,
                proof_body="",
                skipped=True,
                prove_summary=reason,
            )
        if adv_flags:
            with _print_lock:
                print(f"         adversarial: WARNING — {adv_flags} (proceeding with penalty)")

        if translate_only or not tr.validated:
            reason = "translate-only mode" if translate_only else "translation not validated"
            return PipelineResult(
                entry=entry,
                translation=tr,
                proved=False,
                proof_body="",
                skipped=True,
                prove_summary=reason,
            )

        # --- 2.3 Prove ---
        tmp_lean = project_root / "Desol" / f"_tmp_prove_{lean_id}_{i}.lean"
        proved = False
        proof_summary = ""
        records: list = []
        exc_str = ""
        try:
            from mcts_search import run_draft_mcts, run_draft_mcts_parallel
            from prove_with_ponder import (
                _adapt_mcts_params,
                _estimate_theorem_difficulty,
                prove_with_full_draft_repair,
            )

            sig = tr.lean_signature
            sig_clean = re.sub(r":=\s*by\b.*$", "", sig, flags=re.DOTALL).strip()
            sig_clean = re.sub(r":=\s*$", "", sig_clean).strip()
            sig_clean = _force_decl_name(sig_clean, lean_id)
            sig_clean = re.sub(r"^\s*(lemma|def)\b", "theorem", sig_clean, count=1, flags=re.MULTILINE)
            tmp_lean.write_text(
                f"{imports}\n\n{sig_clean} := by\n  sorry\n",
                encoding="utf-8",
            )

            rl.acquire()

            def _run_full_draft() -> tuple[bool, list, str]:
                return prove_with_full_draft_repair(
                    project_root=project_root,
                    file_path=tmp_lean.relative_to(project_root),
                    theorem_name=lean_id,
                    client=client,
                    model=model,
                    repair_rounds=repair_rounds,
                    temperature=temperature,
                    dojo_timeout=dojo_timeout,
                    premise_context=static_premise_context,
                    retrieval_index_path=retrieval_index_path,
                    retrieval_top_k=retrieval_top_k,
                    informal_proof_hint=entry.proof,
                )

            def _run_mcts() -> tuple[bool, list, str]:
                cpu_target = max(0.1, min(mcts_cpu_target, 1.0))
                auto_workers = max(1, int(mp.cpu_count() * cpu_target))
                worker_count = mcts_parallel_workers if mcts_parallel_workers > 0 else auto_workers

                difficulty = _estimate_theorem_difficulty(
                    project_root=project_root,
                    file_path=tmp_lean.relative_to(project_root),
                    theorem_name=lean_id,
                    dojo_timeout=dojo_timeout,
                )
                tuned_workers, tuned_iterations, tuned_variants, tuned_depth, tuning_reason = _adapt_mcts_params(
                    profile=mcts_profile,
                    base_workers=worker_count,
                    iterations=mcts_iterations,
                    repair_variants=mcts_repair_variants,
                    max_depth=mcts_max_depth,
                    difficulty=difficulty,
                )

                if tuned_workers > 1:
                    api_key = os.getenv("MISTRAL_API_KEY", "").strip()
                    if api_key:
                        ok_mcts, recs, summ, worker_results = run_draft_mcts_parallel(
                            project_root=project_root,
                            file_path=tmp_lean.relative_to(project_root),
                            theorem_name=lean_id,
                            api_key=api_key,
                            model=model,
                            total_iterations=tuned_iterations,
                            num_workers=tuned_workers,
                            repair_variants=tuned_variants,
                            max_depth=tuned_depth,
                            exploration_c=mcts_exploration_c,
                            temperature=temperature,
                            dojo_timeout=dojo_timeout,
                            premise_context=static_premise_context,
                            retrieval_index_path=retrieval_index_path,
                            retrieval_top_k=retrieval_top_k,
                            informal_proof_hint=entry.proof,
                        )
                        worker_summary_bits = [
                            (
                                f"worker {w.worker_id}: "
                                f"ok={w.ok}, best_value={w.best_value:.3f}, "
                                f"records={len(w.records)}"
                                + (f", error={w.error}" if w.error else "")
                            )
                            for w in sorted(worker_results, key=lambda x: x.worker_id)
                        ]
                        if worker_summary_bits:
                            summ = summ + " | " + " ; ".join(worker_summary_bits)
                    else:
                        ok_mcts, recs, summ = run_draft_mcts(
                            project_root=project_root,
                            file_path=tmp_lean.relative_to(project_root),
                            theorem_name=lean_id,
                            client=client,
                            model=model,
                            iterations=tuned_iterations,
                            repair_variants=tuned_variants,
                            max_depth=tuned_depth,
                            exploration_c=mcts_exploration_c,
                            temperature=temperature,
                            dojo_timeout=dojo_timeout,
                            premise_context=static_premise_context,
                            retrieval_index_path=retrieval_index_path,
                            retrieval_top_k=retrieval_top_k,
                            informal_proof_hint=entry.proof,
                        )
                        summ = summ + " | parallel requested but MISTRAL_API_KEY unavailable for process workers"
                else:
                    ok_mcts, recs, summ = run_draft_mcts(
                        project_root=project_root,
                        file_path=tmp_lean.relative_to(project_root),
                        theorem_name=lean_id,
                        client=client,
                        model=model,
                        iterations=tuned_iterations,
                        repair_variants=tuned_variants,
                        max_depth=tuned_depth,
                        exploration_c=mcts_exploration_c,
                        temperature=temperature,
                        dojo_timeout=dojo_timeout,
                        premise_context=static_premise_context,
                        retrieval_index_path=retrieval_index_path,
                        retrieval_top_k=retrieval_top_k,
                        informal_proof_hint=entry.proof,
                    )

                summ = (
                    summ
                    + " | "
                    + (
                        f"profile={mcts_profile} ({tuning_reason}), "
                        f"difficulty={difficulty.level}:{difficulty.score:.2f}, "
                        f"goals={difficulty.goals}, state_chars={difficulty.state_chars}, hyps={difficulty.hypotheses}, "
                        f"workers={tuned_workers}, iterations={tuned_iterations}, "
                        f"variants={tuned_variants}, depth={tuned_depth}"
                    )
                )
                return ok_mcts, recs, summ

            if prove_mode == "full-draft":
                proved, records, proof_summary = _run_full_draft()
            elif prove_mode in ("state-mcts", "hierarchical-state"):
                try:
                    from mcts_search import run_hierarchical_state_mcts, run_state_mcts
                    _smcts_fn = run_hierarchical_state_mcts if prove_mode == "hierarchical-state" else run_state_mcts
                    proved, tactics, proof_summary = _smcts_fn(
                        project_root=project_root,
                        theorem_statement=sig_clean,
                        client=client,
                        model=model,
                        iterations=mcts_iterations,
                        n_tactics=mcts_repair_variants,
                        max_depth=mcts_max_depth,
                        repl_timeout=float(dojo_timeout),
                        premise_context=static_premise_context,
                        retrieval_index_path=retrieval_index_path,
                        retrieval_top_k=retrieval_top_k,
                    )
                    records = [{"tactic": t, "result": "state-advanced"} for t in tactics] if proved else []
                except Exception as smcts_exc:
                    proved = False
                    records = []
                    proof_summary = f"{prove_mode} exception: {smcts_exc}"
            elif prove_mode == "mcts-draft":
                try:
                    proved, records, proof_summary = _run_mcts()
                except Exception as mcts_exc:
                    proved = False
                    records = []
                    proof_summary = f"mcts-draft exception: {mcts_exc}"
            else:
                try:
                    mcts_ok, mcts_records, mcts_summary = _run_mcts()
                except Exception as mcts_exc:
                    mcts_ok, mcts_records, mcts_summary = False, [], f"mcts exception: {mcts_exc}"
                if mcts_ok:
                    proved, records, proof_summary = mcts_ok, mcts_records, f"auto->mcts: {mcts_summary}"
                else:
                    fd_ok, fd_records, fd_summary = _run_full_draft()
                    proved = fd_ok
                    records = fd_records
                    proof_summary = (
                        f"auto: mcts failed ({mcts_summary}); "
                        f"fallback full-draft -> {'SUCCESS' if fd_ok else 'FAILED'}: {fd_summary}"
                    )
        except Exception as exc:
            with _print_lock:
                print(f"         prove: EXCEPTION — {exc}")
            proved = False
            proof_summary = str(exc)
            records = []
            exc_str = str(exc)
        finally:
            tmp_lean.unlink(missing_ok=True)

        proof_body = ""
        if proved:
            tactic_lines = []
            for r in records:
                result = r.get("result", "") if isinstance(r, dict) else getattr(r, "result", "")
                tactic = r.get("tactic", "") if isinstance(r, dict) else getattr(r, "tactic", "")
                if result in ("state-advanced", "proof-finished") and tactic:
                    tactic_lines.append(tactic)
            proof_body = "\n".join(f"  {t}" for t in tactic_lines)

        with _print_lock:
            print(f"         prove: {'SUCCESS' if proved else 'FAILED'} — {proof_summary[:80]}")

        return PipelineResult(
            entry=entry,
            translation=tr,
            proved=proved,
            proof_body=proof_body,
            prove_summary=proof_summary,
            step_records=_records_to_dicts(records),
            exception=exc_str,
        )

    workers = max(1, parallel_theorems)
    if workers == 1:
        results: list[PipelineResult] = [
            _process_entry(i, entry) for i, entry in enumerate(entries, start=1)
        ]
    else:
        results_map: dict[int, PipelineResult] = {}
        with ThreadPoolExecutor(max_workers=workers) as executor:
            futures = {
                executor.submit(_process_entry, i, entry): i
                for i, entry in enumerate(entries, start=1)
            }
            for future in as_completed(futures):
                idx = futures[future]
                results_map[idx] = future.result()
        results = [results_map[i] for i in range(1, n + 1)]

    # --- Write output .lean file ---
    _write_lean_file(
        out_lean,
        source_label=label,
        results=results,
        imports=imports,
    )

    ledger_entries: list[dict] = []
    for r in results:
        lean_id = _lean_name(r.entry.name)
        sig_clean = re.sub(r"\s*:=\s*by\s*$", "", r.translation.lean_signature).strip()
        ledger = build_ledger_entry(
            theorem_name=lean_id,
            lean_file=str(out_lean),
            lean_statement=sig_clean,
            proved=r.proved,
            step_records=r.step_records,
            proof_text=r.proof_body,
            error_message=r.exception or r.prove_summary or r.translation.last_error,
            proof_mode=prove_mode,
            rounds_used=len(r.step_records),
            provenance=ProvenanceLink(
                paper_id=paper_id,
                label=r.entry.name,
                section="",
                cited_refs=cited_refs,
            ),
            project_root=project_root,
            ledger_root=project_root / "output" / "verification_ledgers",
            translation_validated=r.translation.validated,
            translation_rounds_used=r.translation.rounds_used,
            translation_uncertainty_flags=r.translation.uncertainty_flags,
            translation_confidence=r.translation.confidence,
            had_exception=bool(r.exception),
        )
        ledger_entries.append(ledger.to_dict())

    ledger_root = project_root / "output" / "verification_ledgers"
    ledger_path = save_ledger(
        paper_id=paper_id,
        entries=ledger_entries,
        output_root=ledger_root,
        metadata={
            "paper_id": paper_id,
            "source_label": label,
            "prove_mode": prove_mode,
            "model": model,
            "entry_count": len(ledger_entries),
        },
    )

    if write_kg:
        try:
            from kg_writer import build_kg

            kg_out = kg_root if kg_root is not None else (project_root / "output" / "kg")
            kg_summary = build_kg(
                ledger_dir=ledger_root,
                kg_root=kg_out,
                paper=paper_id,
            )
            print(
                "       kg:          "
                f"trusted={kg_summary.trusted} conditional={kg_summary.conditional} "
                f"diagnostics={kg_summary.diagnostics}"
            )
        except Exception as exc:
            print(f"       kg:          failed ({exc})")

    proved_count = sum(1 for r in results if r.proved)
    translated_count = sum(1 for r in results if r.translation.validated)
    print(f"\n[done] {len(results)} theorems processed")
    print(f"       translated:  {translated_count}/{len(results)}")
    print(f"       proved:      {proved_count}/{len(results)}")
    print(f"       output:      {out_lean}")
    print(f"       ledger:      {ledger_path}")
    return results


def _write_lean_file(
    out_path: Path,
    *,
    source_label: str,
    results: list[PipelineResult],
    imports: str,
) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    parts: list[str] = [
        _LEAN_HEADER_TEMPLATE.format(
            paper_id=source_label,
            timestamp=time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime()),
            imports=imports.strip(),
        )
    ]

    for r in results:
        entry = r.entry
        lean_id = _lean_name(entry.name)
        latex_stmt_short = " ".join(entry.statement.split())[:120]

        # Strip trailing `:= by` from signature so templates don't produce
        # double `:= by` when the model includes it in the signature.
        sig_clean = re.sub(r"\s*:=\s*by\s*$", "", r.translation.lean_signature).strip()

        if not r.translation.validated:
            parts.append(_SORRY_STUB_TEMPLATE.format(
                kind=entry.kind,
                name=entry.name,
                latex_stmt=latex_stmt_short,
                error=r.translation.last_error[:80],
                signature=sig_clean[:200],
                lean_name=lean_id,
            ))
        elif r.proved and r.proof_body.strip():
            parts.append(_PROVED_TEMPLATE.format(
                kind=entry.kind,
                name=entry.name,
                signature=sig_clean,
                proof_body=r.proof_body,
            ))
        else:
            parts.append(_UNPROVED_TEMPLATE.format(
                kind=entry.kind,
                name=entry.name,
                signature=sig_clean,
            ))

    parts.append(_LEAN_FOOTER)
    out_path.write_text("".join(parts), encoding="utf-8")


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="arxiv paper → Lean 4 proof file")
    p.add_argument("paper_id", help="arxiv ID, e.g. 2301.04567")
    p.add_argument("--out", default="", help="Output .lean file path")
    p.add_argument("--work-dir", default="", help="Working directory for source extraction")
    p.add_argument("--project-root", default=".", help="Lean project root")
    p.add_argument("--model", default="", help="Mistral model (defaults to MISTRAL_MODEL env)")
    p.add_argument(
        "--kinds",
        default="theorem,lemma,proposition,corollary",
        help="Comma-separated theorem kinds to process",
    )
    p.add_argument("--max-theorems", type=int, default=0, help="Cap number of theorems (0 = all)")
    p.add_argument(
        "--translate-only",
        action="store_true",
        help="Only translate statements to Lean signatures; skip proof search",
    )
    p.add_argument("--repair-rounds", type=int, default=5)
    p.add_argument(
        "--prove-mode",
        choices=["full-draft", "mcts-draft", "auto", "state-mcts", "hierarchical-state"],
        default="auto",
        help="Proof mode per theorem: full-draft, mcts-draft, auto, state-mcts, or hierarchical-state",
    )
    p.add_argument(
        "--premise-file",
        default="",
        help="Path to .toon knowledge graph/inventory for static premise injection",
    )
    p.add_argument(
        "--premise-namespace",
        default="ProbabilityTheory",
        help="Namespace filter used when loading --premise-file",
    )
    p.add_argument(
        "--retrieval-index",
        default="data/mathlib_embeddings",
        help="Path to premise retrieval index",
    )
    p.add_argument("--retrieval-top-k", type=int, default=12)
    p.add_argument(
        "--imports",
        default="",
        help="Override Lean import header (default: broad baseline + auto-expansion from premise index)",
    )
    p.add_argument("--temperature", type=float, default=0.2)
    p.add_argument("--dojo-timeout", type=int, default=600)
    p.add_argument(
        "--mcts-profile",
        choices=["fixed", "throughput", "depth", "hybrid"],
        default="throughput",
        help="Draft-MCTS profile used when prove-mode includes mcts",
    )
    p.add_argument("--mcts-iterations", type=int, default=24)
    p.add_argument("--mcts-repair-variants", type=int, default=2)
    p.add_argument("--mcts-max-depth", type=int, default=3)
    p.add_argument("--mcts-exploration-c", type=float, default=1.4)
    p.add_argument("--mcts-parallel-workers", type=int, default=0)
    p.add_argument("--mcts-cpu-target", type=float, default=0.8)
    p.add_argument(
        "--parallel-theorems",
        type=int,
        default=4,
        help="Number of theorems to translate/prove in parallel (default: 4)",
    )
    p.add_argument(
        "--api-rate",
        type=float,
        default=4.0,
        help="Max API calls per second across all threads (default: 4.0)",
    )
    p.add_argument(
        "--write-kg",
        action="store_true",
        help="Build KG layers/manifests from produced ledger after pipeline run",
    )
    p.add_argument(
        "--kg-root",
        default="",
        help="Override KG output root (default: output/kg)",
    )
    return p


def main() -> int:
    load_dotenv()
    args = _build_parser().parse_args()

    api_key = os.getenv("MISTRAL_API_KEY", "").strip()
    if not api_key:
        print("[fail] MISTRAL_API_KEY is not set", file=sys.stderr)
        return 1

    model = args.model.strip() or os.getenv("MISTRAL_MODEL", "labs-leanstral-2603").strip()
    if not model:
        print("[fail] no model configured", file=sys.stderr)
        return 1

    try:
        from mistralai import Mistral
    except ImportError:
        from mistralai.client import Mistral  # type: ignore[no-redef]

    client = Mistral(api_key=api_key)

    paper_id = args.paper_id.removeprefix("arxiv:").strip()
    safe_id = paper_id.replace("/", "_")
    project_root = Path(args.project_root).resolve()
    out_lean = Path(args.out) if args.out else project_root / "output" / f"{safe_id}.lean"
    work_dir = Path(args.work_dir) if args.work_dir else Path(f"/tmp/arxiv_{safe_id}")
    kinds = {k.strip().lower() for k in args.kinds.split(",") if k.strip()}

    try:
        run_pipeline(
            paper_id=paper_id,
            project_root=project_root,
            out_lean=out_lean,
            work_dir=work_dir,
            client=client,
            model=model,
            kinds=kinds,
            max_theorems=args.max_theorems,
            translate_only=args.translate_only,
            repair_rounds=args.repair_rounds,
            retrieval_index_path=args.retrieval_index,
            retrieval_top_k=args.retrieval_top_k,
            premise_file=args.premise_file,
            premise_namespace=args.premise_namespace,
            prove_mode=args.prove_mode,
            mcts_profile=args.mcts_profile,
            mcts_iterations=args.mcts_iterations,
            mcts_repair_variants=args.mcts_repair_variants,
            mcts_max_depth=args.mcts_max_depth,
            mcts_exploration_c=args.mcts_exploration_c,
            mcts_parallel_workers=args.mcts_parallel_workers,
            mcts_cpu_target=args.mcts_cpu_target,
            imports=args.imports,
            temperature=args.temperature,
            dojo_timeout=args.dojo_timeout,
            parallel_theorems=args.parallel_theorems,
            rate_limiter=_RateLimiter(rate=args.api_rate),
            write_kg=args.write_kg,
            kg_root=(Path(args.kg_root) if args.kg_root else None),
        )
    except KeyboardInterrupt:
        print("\n[interrupted]", file=sys.stderr)
        return 1
    except Exception as exc:
        print(f"[fail] {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
