#!/usr/bin/env python3
"""Run arXiv -> Lean pipeline sequentially across many papers with cleanup between runs.

Workflow per paper:
1) Fetch arXiv source + run translation/proof pipeline
2) Store resulting .lean output in output directory
3) Delete fetched source/work directory (unless --keep-source)
4) Continue with next paper
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path


@dataclass
class CycleResult:
    paper_id: str
    ok: bool
    output_lean: str
    work_dir: str
    elapsed_s: float
    return_code: int
    error: str = ""
    output_sha256: str = ""
    verification_counts: dict[str, int] = field(default_factory=dict)


def _compute_sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _output_artifact_is_valid(*, paper_id: str, output_lean: str, expected_sha256: str = "") -> bool:
    if not output_lean:
        return False
    out = Path(output_lean)
    if (not out.exists()) or (not out.is_file()):
        return False
    if out.stat().st_size < 64:
        return False

    try:
        text = out.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return False

    # Basic sanity for generated artifacts: expected header and paper id.
    if "Auto-generated by arxiv_to_lean.py" not in text:
        return False
    if f"Paper: {paper_id}" not in text:
        return False
    if "namespace ArxivPaper" not in text:
        return False

    # Optional integrity gate against manifest tampering.
    if expected_sha256:
        try:
            if _compute_sha256(out) != expected_sha256:
                return False
        except Exception:
            return False

    return True


def _load_paper_ids(args: argparse.Namespace) -> list[str]:
    ids: list[str] = [p.removeprefix("arxiv:").strip() for p in args.paper_ids if p.strip()]
    source_file = args.queue_file or args.paper_file
    if source_file:
        content = Path(source_file).read_text(encoding="utf-8")
        for line in content.splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            for token in line.split(","):
                paper = token.removeprefix("arxiv:").strip()
                if paper:
                    ids.append(paper)

    deduped: list[str] = []
    seen: set[str] = set()
    for p in ids:
        if p not in seen:
            seen.add(p)
            deduped.append(p)
    return deduped


def _load_manifest_results(manifest_path: Path) -> list[CycleResult]:
    if not manifest_path.exists():
        return []
    try:
        raw = json.loads(manifest_path.read_text(encoding="utf-8"))
    except Exception:
        return []

    results: list[CycleResult] = []
    if not isinstance(raw, list):
        return results
    for item in raw:
        if not isinstance(item, dict):
            continue
        try:
            results.append(
                CycleResult(
                    paper_id=str(item.get("paper_id", "")),
                    ok=bool(item.get("ok", False)),
                    output_lean=str(item.get("output_lean", "")),
                    work_dir=str(item.get("work_dir", "")),
                    elapsed_s=float(item.get("elapsed_s", 0.0)),
                    return_code=int(item.get("return_code", 1)),
                    error=str(item.get("error", "")),
                    output_sha256=str(item.get("output_sha256", "")),
                    verification_counts=dict(item.get("verification_counts", {})),
                )
            )
        except Exception:
            continue
    return results


def _load_verification_counts(*, project_root: Path, paper_id: str) -> dict[str, int]:
    safe = paper_id.replace("/", "_").replace(":", "_")
    ledger = project_root / "output" / "verification_ledgers" / f"{safe}.json"
    if not ledger.exists():
        return {}
    try:
        rows = json.loads(ledger.read_text(encoding="utf-8"))
    except Exception:
        return {}
    if not isinstance(rows, list):
        return {}
    counts: dict[str, int] = {}
    for row in rows:
        if not isinstance(row, dict):
            continue
        status = str(row.get("status", "")).strip()
        if not status:
            continue
        counts[status] = counts.get(status, 0) + 1
    return counts


def _already_completed_ok(prior: list[CycleResult]) -> set[str]:
    completed: set[str] = set()
    for entry in prior:
        if not entry.ok:
            continue
        if _output_artifact_is_valid(
            paper_id=entry.paper_id,
            output_lean=entry.output_lean,
            expected_sha256=entry.output_sha256,
        ):
            completed.add(entry.paper_id)
    return completed


def _run_one(
    *,
    project_root: Path,
    paper_id: str,
    output_dir: Path,
    work_root: Path,
    args: argparse.Namespace,
) -> CycleResult:
    safe = paper_id.replace("/", "_")
    out_lean = output_dir / f"{safe}.lean"
    work_dir = work_root / safe

    cmd = [
        sys.executable,
        "scripts/arxiv_to_lean.py",
        paper_id,
        "--project-root",
        str(project_root),
        "--out",
        str(out_lean),
        "--work-dir",
        str(work_dir),
        "--repair-rounds",
        str(args.repair_rounds),
        "--parallel-theorems",
        str(args.parallel_theorems),
        "--api-rate",
        str(args.api_rate),
        "--retrieval-index",
        args.retrieval_index,
        "--retrieval-top-k",
        str(args.retrieval_top_k),
        "--premise-file",
        args.premise_file,
        "--premise-namespace",
        args.premise_namespace,
        "--prove-mode",
        args.prove_mode,
        "--mcts-profile",
        args.mcts_profile,
        "--mcts-iterations",
        str(args.mcts_iterations),
        "--mcts-repair-variants",
        str(args.mcts_repair_variants),
        "--mcts-max-depth",
        str(args.mcts_max_depth),
        "--mcts-exploration-c",
        str(args.mcts_exploration_c),
        "--mcts-parallel-workers",
        str(args.mcts_parallel_workers),
        "--mcts-cpu-target",
        str(args.mcts_cpu_target),
        "--temperature",
        str(args.temperature),
        "--dojo-timeout",
        str(args.dojo_timeout),
    ]

    if args.max_theorems > 0:
        cmd.extend(["--max-theorems", str(args.max_theorems)])
    if args.translate_only:
        cmd.append("--translate-only")
    if args.model:
        cmd.extend(["--model", args.model])
    # Note: we do not pass per-paper --write-kg here; kg_writer with a single
    # paper would overwrite JSONL layers for other papers. Use --write-kg on
    # arxiv_cycle to run one full ledger→KG merge when the batch finishes.

    start = time.time()
    proc = subprocess.run(cmd, cwd=project_root)
    elapsed = time.time() - start

    has_output = out_lean.exists()
    ok = (proc.returncode == 0) and has_output
    output_sha256 = ""
    if has_output:
        try:
            output_sha256 = _compute_sha256(out_lean)
        except Exception:
            output_sha256 = ""

    verification_counts = _load_verification_counts(project_root=project_root, paper_id=paper_id)

    error_msg = ""
    if proc.returncode != 0:
        error_msg = "pipeline failed"
    elif not has_output:
        error_msg = "no output lean produced (likely no theorem environments)"
    elif not _output_artifact_is_valid(
        paper_id=paper_id,
        output_lean=str(out_lean),
        expected_sha256=output_sha256,
    ):
        ok = False
        error_msg = "output artifact failed integrity checks"

    result = CycleResult(
        paper_id=paper_id,
        ok=ok,
        output_lean=str(out_lean),
        work_dir=str(work_dir),
        elapsed_s=elapsed,
        return_code=proc.returncode,
        error=error_msg,
        output_sha256=output_sha256,
        verification_counts=verification_counts,
    )

    if not args.keep_source:
        shutil.rmtree(work_dir, ignore_errors=True)

    return result


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Cycle through arXiv papers and cleanup source after each run")
    p.add_argument("paper_ids", nargs="*", help="arXiv IDs (e.g. 2301.04567)")
    p.add_argument("--paper-file", default="", help="File with paper IDs (newline or comma-separated)")
    p.add_argument("--queue-file", default="", help="Curated queue file with paper IDs (newline or comma-separated)")
    p.add_argument("--project-root", default=".", help="DESol project root")
    p.add_argument("--output-dir", default="output/arxiv_cycle", help="Directory for final .lean outputs")
    p.add_argument("--work-root", default="/tmp/desol_arxiv_cycle", help="Temp root for fetched arXiv sources")
    p.add_argument("--keep-source", action="store_true", help="Do not delete fetched source/work dirs")
    p.add_argument("--continue-on-fail", action="store_true", help="Continue to next paper on failures")
    p.add_argument("--manifest", default="", help="Write manifest JSON (default: output-dir/manifest.json)")
    p.add_argument(
        "--resume",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Skip papers already marked successful in manifest (default: enabled)",
    )

    p.add_argument("--model", default="", help="Mistral model override")
    p.add_argument("--translate-only", action="store_true")
    p.add_argument("--max-theorems", type=int, default=0)
    p.add_argument("--repair-rounds", type=int, default=5)
    p.add_argument("--parallel-theorems", type=int, default=4)
    p.add_argument("--api-rate", type=float, default=4.0)
    p.add_argument("--retrieval-index", default="data/mathlib_embeddings")
    p.add_argument("--retrieval-top-k", type=int, default=12)
    p.add_argument(
        "--premise-file",
        default="knowledge/dependency_graph.toon",
        help="Path to .toon premise graph/inventory injected into proving loop",
    )
    p.add_argument(
        "--premise-namespace",
        default="ProbabilityTheory",
        help="Namespace filter used for --premise-file",
    )
    p.add_argument(
        "--prove-mode",
        choices=["full-draft", "mcts-draft", "auto"],
        default="auto",
        help="Proof mode used by arxiv_to_lean (default: auto)",
    )
    p.add_argument(
        "--mcts-profile",
        choices=["fixed", "throughput", "depth", "hybrid"],
        default="throughput",
        help="Draft-MCTS profile used when prove-mode includes mcts",
    )
    p.add_argument("--mcts-iterations", type=int, default=24)
    p.add_argument("--mcts-repair-variants", type=int, default=2)
    p.add_argument("--mcts-max-depth", type=int, default=3)
    p.add_argument("--mcts-exploration-c", type=float, default=1.4)
    p.add_argument("--mcts-parallel-workers", type=int, default=0)
    p.add_argument("--mcts-cpu-target", type=float, default=0.8)
    p.add_argument("--temperature", type=float, default=0.2)
    p.add_argument("--dojo-timeout", type=int, default=600)
    p.add_argument(
        "--write-kg",
        action="store_true",
        help="After the full cycle, rebuild KG from all ledgers (kg_writer.build_kg, paper filter off)",
    )
    p.add_argument(
        "--kg-root",
        default="output/kg",
        help="KG output root used with --write-kg (default: output/kg)",
    )
    return p


def main() -> int:
    args = _build_parser().parse_args()
    project_root = Path(args.project_root).resolve()
    output_dir = (project_root / args.output_dir).resolve()
    work_root = Path(args.work_root).resolve()

    paper_ids = _load_paper_ids(args)
    if not paper_ids:
        print("[fail] no paper IDs provided")
        return 1

    output_dir.mkdir(parents=True, exist_ok=True)
    work_root.mkdir(parents=True, exist_ok=True)

    manifest_path = Path(args.manifest).resolve() if args.manifest else output_dir / "manifest.json"
    results: list[CycleResult] = _load_manifest_results(manifest_path) if args.resume else []
    completed_ok = _already_completed_ok(results) if args.resume else set()

    if args.resume:
        print(
            f"[resume] loaded {len(results)} prior results, "
            f"completed_ok={len(completed_ok)} from {manifest_path}"
        )

    total = len(paper_ids)
    for idx, paper_id in enumerate(paper_ids, start=1):
        if paper_id in completed_ok:
            print(f"\n[{idx}/{total}] paper={paper_id}")
            print("[skip] already completed successfully (manifest + integrity-checked output)")
            continue

        print(f"\n[{idx}/{total}] paper={paper_id}")
        res = _run_one(
            project_root=project_root,
            paper_id=paper_id,
            output_dir=output_dir,
            work_root=work_root,
            args=args,
        )
        results.append(res)

        status = "ok" if res.ok else "fail"
        print(
            f"[{status}] paper={res.paper_id} return_code={res.return_code} "
            f"elapsed={res.elapsed_s:.1f}s output={res.output_lean}"
        )
        if res.verification_counts:
            print(f"[verify] {res.verification_counts}")
        if not args.keep_source:
            print(f"[cleanup] removed {res.work_dir}")

        manifest_path.write_text(
            json.dumps([asdict(r) for r in results], indent=2),
            encoding="utf-8",
        )

        if res.ok:
            completed_ok.add(res.paper_id)

        if (not res.ok) and (not args.continue_on_fail):
            print("[stop] failure encountered; use --continue-on-fail to keep cycling")
            return 1

    ok_count = sum(1 for r in results if r.ok)
    print(f"\n[done] completed {len(results)} papers, success={ok_count}/{len(results)}")
    print(f"[manifest] {manifest_path}")

    if args.write_kg:
        ledger_dir = project_root / "output" / "verification_ledgers"
        kg_root = (project_root / args.kg_root).resolve()
        try:
            from kg_writer import build_kg

            summary = build_kg(ledger_dir=ledger_dir, kg_root=kg_root, paper="")
            print(
                "[kg] rebuilt from all ledgers: "
                f"papers={summary.papers} entries={summary.entries} "
                f"trusted={summary.trusted} conditional={summary.conditional} "
                f"diagnostics={summary.diagnostics} root={kg_root}"
            )
        except Exception as exc:
            print(f"[kg] build failed: {exc}", file=sys.stderr)

    return 0 if ok_count == len(results) else 1


if __name__ == "__main__":
    sys.exit(main())
