#!/usr/bin/env python3
"""Promote pipeline-generated proofs to the curated PaperProofs companion file.

When a candidate proof produced by the whole-proof generator (or any
first-pass tactic chain) passes lake validation AND survives the
integrity audit, this module appends a `<name>__autoproved` companion
declaration to `Desol/PaperProofs/Paper_<id>.lean`.

Two reasons this exists:

  1. **Compounding in-context examples.** ``extract_audited_core_hints``
     walks the entire ``Desol/PaperProofs/`` tree to build the
     paper-local hint cache consumed by
     ``leanstral_whole_proof_generator`` and ``lemma_factor_v2``. The
     more curated companions there are, the better the next round of
     B3-style few-shot proof generation gets — see commit ``4d7c0e6``
     for the original "compounding" round.

  2. **Regression protection.** ``output/<paper>.lean`` is a generated
     artifact and is not committed; the proof text in the ledger is the
     only canonical record of what was proved. Mirroring the proof into
     ``Desol/PaperProofs/Paper_<id>.lean`` means future prelude/Mathlib
     upgrades that break the proof will break the per-paper Lean
     module's elaboration LOUDLY (rather than silently invalidating an
     ephemeral ledger row).

Pre-conditions (caller-enforced — this module does NOT re-check them
because the caller is in the best position to know):

  * ``proof_body`` passed
    ``leanstral_whole_proof_generator._contains_forbidden_token``;
  * ``lean_statement`` passed
    ``translator._translate._is_trivialized_signature``;
  * ``proof_body`` validated lake-in-context against ``output/<id>.lean``.

This module enforces an additional belt-and-braces check on its own
inputs (forbidden tokens + trivialization heuristics), so a buggy caller
that forgets one of the pre-conditions cannot accidentally write a
``sorry``-bodied or ``: True``-shaped declaration into the curated
file. The optional ``validate_elaboration`` callback gives the caller a
final hook to lake-verify the rewritten companion file before commit.

The directory ``Desol/PaperProofs/`` is COMMITTED evidence, so the write
is atomic: the new content goes to a ``.tmp`` sibling, optionally
validates, then ``os.replace``-moves into place.
"""
from __future__ import annotations

import hashlib
import os
import re
import sys
from pathlib import Path
from typing import Any, Callable, Optional

# Reuse the canonical forbidden-token + trivialization gates rather than
# re-implementing them here. Import paths are repo-relative.
_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

try:
    from leanstral_whole_proof_generator import (
        _contains_forbidden_token,  # type: ignore[attr-defined]
    )
except Exception:  # pragma: no cover - defensive
    def _contains_forbidden_token(body: str) -> Optional[str]:  # type: ignore[misc]
        return None

try:
    from translator._translate import (
        _is_trivialized_signature,  # type: ignore[attr-defined]
    )
except Exception:  # pragma: no cover - defensive
    def _is_trivialized_signature(sig: str) -> bool:  # type: ignore[misc]
        return False


AUTOPROVED_SUFFIX = "__autoproved"

# Markers that delimit the auto-promoted section in
# ``Desol/PaperProofs/Paper_<id>.lean``. Anything between the BEGIN/END
# tags is owned by this script; outside that block is curated content
# that we never touch. The markers are full-line Lean comments so the
# file remains valid Lean.
SECTION_BEGIN = "-- BEGIN autoproved companions (managed by autoproved_promotion.py)"
SECTION_END = "-- END autoproved companions"

_SECTION_HEADER = (
    "-- ==========================================================\n"
    "-- Pipeline-auto-promoted proofs.\n"
    "-- These were generated by leanstral_whole_proof_generator and\n"
    "-- audit-survived. They are kept here so future repository\n"
    "-- changes (prelude updates, Mathlib upgrades) break them\n"
    "-- loudly rather than silently.\n"
    "-- ==========================================================\n"
)


# --- Helpers --------------------------------------------------------------


def _safe_module_id(paper_id: str) -> str:
    """Mirror of ``build_reliable_paper_core._safe_id`` / formalize-paper's
    safe-id transform: replace any non-alphanumeric char with `_`. Keeps
    output paths stable with the rest of the pipeline.
    """
    return re.sub(r"[^A-Za-z0-9_]", "_", str(paper_id).strip())


def autoproved_target_path(project_root: Path, paper_id: str) -> Path:
    """Return the path to ``Desol/PaperProofs/Paper_<id>.lean`` for a paper.

    The module mirrors the canonical curated file location used by
    ``formalize_paper_full._detect_curated_paper_package`` and
    ``extract_audited_core_hints.walk_paper_proofs_files``.
    """
    return (
        Path(project_root)
        / "Desol"
        / "PaperProofs"
        / f"Paper_{_safe_module_id(paper_id)}.lean"
    )


def _theorem_short_name(name: str) -> str:
    """Strip any namespace qualification (``Foo.Bar.thm`` -> ``thm``)."""
    return name.rsplit(".", 1)[-1] if name else name


def _strip_existing_proof_body_suffix(lean_statement: str) -> str:
    """Strip a trailing ``:= by ...`` / ``:= rfl`` / etc. tail so we can
    rebuild the declaration with a fresh proof body. Preserves a
    trailing newline-free signature.
    """
    out = re.sub(r":=\s*by\b.*$", "", lean_statement or "", flags=re.DOTALL).strip()
    out = re.sub(r":=\s*$", "", out).strip()
    return out


def _rename_theorem_head(lean_statement: str, new_name: str) -> str:
    """Replace the first ``theorem <oldname>`` (or ``lemma``) head with
    ``theorem <new_name>``. Drops any leading ``noncomputable`` /
    ``private`` modifier (which we never want in the companion).
    """
    sig = _strip_existing_proof_body_suffix(lean_statement)
    head_re = re.compile(
        r"^\s*(?:noncomputable\s+|private\s+)?(?:theorem|lemma)\s+[A-Za-z_][A-Za-z0-9_'\.]*",
    )
    m = head_re.match(sig)
    if not m:
        # No recognizable head — fall back to prepending a fresh signature.
        return f"theorem {new_name} {sig}"
    return f"theorem {new_name}" + sig[m.end():]


def _indent_proof_body(body: str) -> str:
    """Indent a proof body by 2 spaces, line by line. The body comes in
    as the LLM produced it (no ``:= by`` prefix); we attach the
    ``:= by`` here so the on-disk shape is uniform.
    """
    body = (body or "").rstrip()
    if not body:
        return "  sorry  -- intentionally invalid; would be caught by validate_elaboration"
    lines = body.splitlines()
    # Drop a leading blank line if present.
    while lines and not lines[0].strip():
        lines.pop(0)
    out_lines = []
    for ln in lines:
        if ln.strip():
            out_lines.append("  " + ln)
        else:
            out_lines.append("")
    return "\n".join(out_lines)


def render_autoproved_decl(
    *, theorem_name: str, lean_statement: str, proof_body: str,
) -> tuple[str, str]:
    """Produce ``(decl_text, autoproved_name)`` for a candidate.

    The output is a single Lean ``theorem <name>__autoproved ... := by
    <indented body>`` block, ready for insertion into the autoproved
    section. The decl is tagged ``@[aesop safe apply]`` so subsequent
    sweeps' aesop calls can use it as a hint — closure compounding.
    Standards-positive: the audit still independently verifies every
    promotion; the attribute only helps downstream proof search.
    """
    short = _theorem_short_name(theorem_name)
    auto_name = f"{short}{AUTOPROVED_SUFFIX}"
    sig = _rename_theorem_head(lean_statement, auto_name)
    decl = f"@[aesop safe apply]\n{sig} := by\n{_indent_proof_body(proof_body)}\n"
    return decl, auto_name


# --- Section read / write -------------------------------------------------


def _parse_existing(file_text: str) -> tuple[str, str, str]:
    """Split ``file_text`` into ``(prefix, managed_block, suffix)`` where
    ``managed_block`` is the content between BEGIN/END section markers
    (without the markers themselves). When the markers are absent,
    ``managed_block`` is empty and the trailing ``end <ns>`` block is
    treated as the suffix.

    The managed block lives just BEFORE the closing ``end PaperProofs``
    / namespace lines so it sits inside the namespace.
    """
    begin_idx = file_text.find(SECTION_BEGIN)
    end_idx = file_text.find(SECTION_END)
    if begin_idx != -1 and end_idx != -1 and end_idx > begin_idx:
        # Trim the BEGIN line + trailing newline; same for END.
        line_end = file_text.find("\n", begin_idx)
        if line_end == -1:
            line_end = begin_idx + len(SECTION_BEGIN)
        prefix = file_text[:begin_idx]
        managed = file_text[line_end + 1:end_idx]
        # Skip the END line itself.
        end_line_end = file_text.find("\n", end_idx)
        if end_line_end == -1:
            end_line_end = end_idx + len(SECTION_END)
        suffix = file_text[end_line_end + 1:]
        return prefix, managed, suffix

    # No section markers yet. Splice them in just before the LAST
    # `end <namespace>` line so the block lives inside the namespace.
    lines = file_text.splitlines(keepends=True)
    insert_at = len(lines)
    for i in range(len(lines) - 1, -1, -1):
        if re.match(r"^\s*end\b", lines[i]):
            insert_at = i
            break
    prefix = "".join(lines[:insert_at])
    suffix = "".join(lines[insert_at:])
    return prefix, "", suffix


def _contains_decl(managed_block: str, auto_name: str) -> bool:
    """Detect whether ``managed_block`` already declares ``auto_name``.
    Uses a word-boundary match on the head ``theorem <auto_name>`` so a
    name that is merely referenced (e.g. in a comment) does not trigger
    a false positive.
    """
    pat = re.compile(r"^\s*theorem\s+" + re.escape(auto_name) + r"\b", re.MULTILINE)
    return bool(pat.search(managed_block or ""))


def _render_managed_section(managed_block: str) -> str:
    """Wrap ``managed_block`` with section markers + the human-readable
    section header. Always emits the same canonical shape so the
    promotion is idempotent across reruns.
    """
    body = managed_block.strip("\n")
    if body:
        body = body + "\n"
    return (
        SECTION_BEGIN + "\n"
        + _SECTION_HEADER
        + "\n"
        + body
        + SECTION_END + "\n"
    )


def _atomic_write(path: Path, content: str) -> None:
    """Atomic write: ``path.tmp`` -> ``os.replace`` -> ``path``. Safe
    against partial writes when the process is killed mid-run.
    """
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(str(tmp), str(path))


# --- Public API -----------------------------------------------------------


class PromotionError(RuntimeError):
    """Raised when the caller violates a pre-condition (e.g. a forbidden
    proof body, a trivialized statement). Distinguishes inputs that are
    fundamentally unsafe from ordinary I/O failures (which return False).
    """


def promote_to_autoproved(
    *,
    paper_id: str,
    theorem_name: str,
    lean_statement: str,
    proof_body: str,
    project_root: Path,
    validate_elaboration: Optional[Callable[[Path], tuple[bool, str]]] = None,
) -> dict[str, Any]:
    """Append (or refresh) a ``<theorem_name>__autoproved`` companion in
    ``Desol/PaperProofs/Paper_<id>.lean``.

    Returns a result dict with at least the keys ``ok`` (bool),
    ``status`` (one of ``written``, ``idempotent``, ``no_change``,
    ``refused_*``, ``validation_failed``), ``path``, ``autoproved_name``,
    and ``sha`` (SHA-256 of the post-write file content; empty when no
    write occurred).

    Caller pre-conditions:
      * ``proof_body`` already passed forbidden-token gate
      * ``lean_statement`` already passed trivialization detector
      * ``proof_body`` already validated lake-in-context against
        ``output/<paper_id>.lean``

    Belt-and-braces: this function ALSO re-checks the first two and
    refuses to write on any violation (returns ``ok=False``, distinct
    ``refused_*`` status). The optional ``validate_elaboration``
    callback is called with the candidate target ``Path`` AFTER the file
    is written; if it returns ``(False, ...)``, the original file
    contents are restored and the function returns
    ``status="validation_failed"``.
    """
    short = _theorem_short_name(theorem_name)
    if not short:
        return {
            "ok": False,
            "status": "refused_empty_name",
            "path": "",
            "autoproved_name": "",
            "sha": "",
        }

    # --- Pre-condition re-check (belt-and-braces) -----------------------
    if _is_trivialized_signature(lean_statement or ""):
        return {
            "ok": False,
            "status": "refused_trivialized_statement",
            "path": "",
            "autoproved_name": "",
            "sha": "",
        }
    tok = _contains_forbidden_token(proof_body or "")
    if tok:
        return {
            "ok": False,
            "status": f"refused_forbidden_token:{tok}",
            "path": "",
            "autoproved_name": "",
            "sha": "",
        }
    if not (proof_body or "").strip():
        return {
            "ok": False,
            "status": "refused_empty_proof_body",
            "path": "",
            "autoproved_name": "",
            "sha": "",
        }

    target = autoproved_target_path(Path(project_root), paper_id)
    if not target.exists():
        return {
            "ok": False,
            "status": "refused_missing_paper_proofs_file",
            "path": str(target),
            "autoproved_name": "",
            "sha": "",
        }

    decl, auto_name = render_autoproved_decl(
        theorem_name=theorem_name,
        lean_statement=lean_statement,
        proof_body=proof_body,
    )

    original_text = target.read_text(encoding="utf-8")
    prefix, managed, suffix = _parse_existing(original_text)

    if _contains_decl(managed, auto_name):
        # Idempotent: don't duplicate.
        return {
            "ok": True,
            "status": "idempotent",
            "path": str(target),
            "autoproved_name": auto_name,
            "sha": hashlib.sha256(original_text.encode("utf-8")).hexdigest(),
        }

    # Append the new decl to the managed block.
    new_managed = (managed.rstrip("\n") + ("\n\n" if managed.strip() else "")
                   + decl.rstrip() + "\n")
    new_section = _render_managed_section(new_managed)

    # Ensure exactly one blank line between prefix and section.
    prefix_clean = prefix.rstrip() + "\n\n" if prefix.strip() else prefix
    suffix_clean = suffix
    if suffix.strip() and not suffix.startswith("\n"):
        suffix_clean = "\n" + suffix

    new_text = prefix_clean + new_section + suffix_clean

    if new_text == original_text:
        # Defensive: nothing changed (shouldn't happen, but don't write
        # spuriously).
        return {
            "ok": True,
            "status": "no_change",
            "path": str(target),
            "autoproved_name": auto_name,
            "sha": hashlib.sha256(original_text.encode("utf-8")).hexdigest(),
        }

    # Atomic write -----------------------------------------------------
    _atomic_write(target, new_text)
    sha = hashlib.sha256(new_text.encode("utf-8")).hexdigest()

    if validate_elaboration is not None:
        try:
            ok, err = validate_elaboration(target)
        except Exception as exc:
            ok, err = False, f"validate_elaboration_raised:{exc}"
        if not ok:
            # Roll back the file to its previous content.
            _atomic_write(target, original_text)
            return {
                "ok": False,
                "status": "validation_failed",
                "path": str(target),
                "autoproved_name": auto_name,
                "sha": "",
                "validation_error": (err or "")[-400:],
            }

    return {
        "ok": True,
        "status": "written",
        "path": str(target),
        "autoproved_name": auto_name,
        "sha": sha,
    }


__all__ = [
    "AUTOPROVED_SUFFIX",
    "SECTION_BEGIN",
    "SECTION_END",
    "PromotionError",
    "autoproved_target_path",
    "promote_to_autoproved",
    "render_autoproved_decl",
]
