#!/usr/bin/env python3
"""Regenerate Desol/PaperImportsAnchor.lean from the present paper-theory modules.

Used by the REPL bootstrap fallback so that when a per-paper output `.lean` file
fails to elaborate, MCTS can still anchor onto an env that has every paper's
namespace available — instead of falling back to a Mathlib-only anchor that
loses all paper-theory definitions and instances.

Idempotent. Run from formalize_paper_full.py whenever a new paper stub is built.
"""

from __future__ import annotations

import argparse
import os
import subprocess
from pathlib import Path

ANCHOR_PATH = Path("Desol/PaperImportsAnchor.lean")
PAPER_THEORY_DIR = Path("Desol/PaperTheory")
HEADER = "-- Auto-generated by scripts/regenerate_paper_imports_anchor.py\n"


def _module_paths(project_root: Path) -> list[str]:
    """Return Lean dotted-import names for every Desol/PaperTheory/Paper_*.lean."""
    base = project_root / PAPER_THEORY_DIR
    if not base.exists():
        return []
    modules: list[str] = []
    for path in sorted(base.rglob("Paper_*.lean")):
        rel = path.relative_to(project_root).with_suffix("")
        modules.append(".".join(rel.parts))
    return modules


def _olean_path(project_root: Path, module: str) -> Path:
    return project_root / ".lake" / "build" / "lib" / "lean" / Path(*module.split(".")).with_suffix(".olean")


def _module_buildable(project_root: Path, module: str, source_path: Path) -> bool:
    """Cheap heuristic: an .olean exists and is newer than its source.

    This avoids running `lake build` per-module (slow). Modules that have never
    built successfully — or whose source is newer than their last successful
    build — are excluded, so the anchor itself stays clean. The caller can
    refresh by running `lake build Desol.PaperTheory` first.
    """
    olean = _olean_path(project_root, module)
    if not olean.exists() or not source_path.exists():
        return False
    try:
        return olean.stat().st_mtime >= source_path.stat().st_mtime
    except OSError:
        return False


def _try_build_missing_olean(
    project_root: Path,
    module: str,
    *,
    timeout_s: int = 240,
    runner=subprocess.run,
) -> bool:
    """Opportunistically run `lake build <module>` when its olean is missing.

    The historical regenerator silently dropped a paper-theory module from the
    anchor whenever its olean was absent — but the only thing producing oleans
    is `lake build`, which previously had a 60s timeout in
    paper_theory_builder.build_paper_theory. A single timeout was enough to
    permanently exclude the module from MCTS's REPL fallback, because the
    anchor never re-tries the build. We now attempt the build here as a
    self-heal step before deciding to exclude. The `runner` parameter is
    injected to make tests hermetic (no real lake invocation).
    """
    try:
        proc = runner(
            ["lake", "build", module],
            cwd=str(project_root),
            capture_output=True,
            text=True,
            timeout=timeout_s,
        )
    except Exception:
        return False
    return getattr(proc, "returncode", 1) == 0


def regenerate(
    project_root: Path,
    *,
    only_buildable: bool = True,
    self_heal_missing_oleans: bool = True,
    build_runner=subprocess.run,
) -> Path:
    out_path = project_root / ANCHOR_PATH
    modules = _module_paths(project_root)
    if only_buildable:
        kept: list[str] = []
        for mod in modules:
            src = project_root / Path(*mod.split(".")).with_suffix(".lean")
            if _module_buildable(project_root, mod, src):
                kept.append(mod)
                continue
            # Self-heal: if the source exists but the olean is missing or stale,
            # try a one-shot `lake build` before giving up.
            if self_heal_missing_oleans and src.exists():
                if _try_build_missing_olean(project_root, mod, runner=build_runner):
                    if _module_buildable(project_root, mod, src):
                        kept.append(mod)
        modules = kept
    lines = [HEADER, "import Mathlib\n"]
    for mod in modules:
        lines.append(f"import {mod}\n")
    lines.append("\nnamespace Desol\n\n")
    lines.append("theorem paper_imports_anchor_trivial : True := by\n")
    lines.append("  trivial\n\n")
    lines.append("end Desol\n")
    new_text = "".join(lines)
    if out_path.exists() and out_path.read_text(encoding="utf-8") == new_text:
        return out_path
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(new_text, encoding="utf-8")
    return out_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate Desol/PaperImportsAnchor.lean")
    parser.add_argument("--project-root", type=Path, default=Path("."))
    args = parser.parse_args()
    out = regenerate(args.project_root.resolve())
    print(f"Regenerated {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
