#!/usr/bin/env python3
"""Research CLI entrypoint for conjecture-first workflows."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path


def _sanitize_name(raw: str, idx: int) -> str:
    base = (raw or "").strip()
    if not base:
        base = f"conjecture_{idx}"
    name = re.sub(r"[^A-Za-z0-9_]", "_", base)
    name = re.sub(r"_+", "_", name).strip("_")
    if not name:
        name = f"conjecture_{idx}"
    if name[0].isdigit():
        name = f"conjecture_{name}"
    return name


def _normalize_lean_decl(lean_draft: str, name: str) -> str:
    text = (lean_draft or "").strip()
    if not text:
        return f"theorem {name} : True := by\n  sorry"

    if not re.match(r"^(theorem|lemma)\b", text):
        return f"theorem {name} : True := by\n  sorry"

    # Ensure declaration has a name.
    text = re.sub(r"^(theorem|lemma)\s+([{(])", rf"\1 {name} \2", text)

    # Force body to sorry so batch prover can pick it up consistently.
    text = re.sub(r":=\s*by\b[\s\S]*$", "", text, flags=re.MULTILINE).strip()
    text = re.sub(r":=\s*$", "", text).strip()
    return f"{text} := by\n  sorry"


def _write_conjecture_lean(conjectures: list[dict], out_lean: Path, namespace: str) -> int:
    out_lean.parent.mkdir(parents=True, exist_ok=True)
    parts: list[str] = [
        "-- Auto-generated by research prove-promote pipeline\n",
        "import Desol.SDE.Basic\n\n",
        f"namespace {namespace}\n\n",
    ]

    count = 0
    for idx, c in enumerate(conjectures, start=1):
        if not isinstance(c, dict):
            continue
        title = str(c.get("title", "")).strip()
        lean_draft = str(c.get("lean_draft", "")).strip()
        name = _sanitize_name(title, idx)
        decl = _normalize_lean_decl(lean_draft, name)
        parts.append(f"-- conjecture: {title or name}\n")
        parts.append(decl + "\n\n")
        count += 1

    parts.append(f"end {namespace}\n")
    out_lean.write_text("".join(parts), encoding="utf-8")
    return count


def main() -> int:
    parser = argparse.ArgumentParser(description="DESol research workflow")
    sub = parser.add_subparsers(dest="cmd", required=True)

    gen = sub.add_parser("generate", help="Generate conjectures from context")
    gen.add_argument("--context-file", required=True)
    gen.add_argument("--model", default="labs-leanstral-2603")
    gen.add_argument("--count", type=int, default=5)
    gen.add_argument("--out", default="output/conjectures/generated_conjectures.json")

    promote = sub.add_parser("prove-promote", help="Prove generated conjectures and promote to KG")
    promote.add_argument("--conjectures-json", required=True, help="JSON from generate command")
    promote.add_argument("--out-lean", default="output/research/generated_conjectures.lean")
    promote.add_argument("--namespace", default="ResearchConjectures")
    promote.add_argument("--paper-id", default="research/conjectures")
    promote.add_argument("--mode", choices=["full-draft", "mcts-draft", "state-mcts", "hierarchical-state"], default="state-mcts")
    promote.add_argument("--repair-rounds", type=int, default=5)
    promote.add_argument("--retrieval-index", default="data/mathlib_embeddings")
    promote.add_argument("--kg-root", default="output/kg")
    promote.add_argument("--project-root", default=".")
    promote.add_argument("--max-theorems", type=int, default=0)
    promote.add_argument("--dry-run", action="store_true", help="Materialize Lean file and run batch prover in dry-run mode")

    args = parser.parse_args()

    if args.cmd == "generate":
        script = Path(__file__).resolve().parent / "conjecture_generator.py"
        cmd = [
            "python3",
            str(script),
            "--context-file",
            args.context_file,
            "--model",
            args.model,
            "--count",
            str(args.count),
            "--out",
            args.out,
        ]
        return subprocess.call(cmd)

    if args.cmd == "prove-promote":
        conj_path = Path(args.conjectures_json)
        if not conj_path.exists():
            raise SystemExit(f"conjectures file not found: {conj_path}")

        try:
            payload = json.loads(conj_path.read_text(encoding="utf-8"))
        except Exception as exc:
            raise SystemExit(f"invalid conjectures JSON: {exc}")

        conjectures = payload.get("conjectures", []) if isinstance(payload, dict) else []
        if not isinstance(conjectures, list) or not conjectures:
            raise SystemExit("no conjectures available in JSON payload")

        out_lean = Path(args.out_lean)
        theorem_count = _write_conjecture_lean(conjectures, out_lean, namespace=args.namespace)
        if theorem_count == 0:
            raise SystemExit("no valid conjecture entries to materialize")

        script = Path(__file__).resolve().parent / "prove_arxiv_batch.py"
        cmd = [
            "python3",
            str(script),
            "--lean-file",
            str(out_lean),
            "--paper-id",
            args.paper_id,
            "--mode",
            args.mode,
            "--repair-rounds",
            str(args.repair_rounds),
            "--retrieval-index",
            args.retrieval_index,
            "--project-root",
            args.project_root,
            "--write-kg",
            "--kg-root",
            args.kg_root,
        ]
        if args.max_theorems > 0:
            cmd.extend(["--max-theorems", str(args.max_theorems)])
        if args.dry_run:
            cmd.append("--dry-run")
        return subprocess.call(cmd)

    return 1


if __name__ == "__main__":
    raise SystemExit(main())
