-- Auto-generated by arxiv_to_lean.py
-- Paper: 2604.21884
-- Generated: 2026-04-26 06:36 UTC

import Desol.SDE.Basic

open MeasureTheory ProbabilityTheory

-- Suppress binder-annotation check: some auto-translated typeclasses may not
-- be recognized as class instances by Lean's binder checker, but are harmless.
set_option checkBinderAnnotations false

namespace ArxivPaper

-- [theorem] thm:baseline-lift
theorem thm_baseline_lift (p_c1 : Prop) (h_c1 : p_c1) : p_c1 := by
  sorry

-- [theorem] prop:cubic-quartic-baseline
theorem prop_cubic_quartic_baseline (p_c1 : Prop) (h_c1 : p_c1) : p_c1 := by
  sorry

-- [theorem] thm:operator-main
-- Statement (LaTeX): [Mixed random operators and no singular centering] Let E_T:=C_TL^2 C_T^1H^{--}. Fix $0<<1$ and $s_2>0$ such that s_2<4-3
-- Translation: PARTIAL — semantic_policy_violation:claim_shape_mismatch:eq->exists,schema_self_check:sche
theorem thm_operator_main {alpha eps theta s2 : ℝ} (halpha : alpha > 3/4) (htheta : 0 < theta ∧ theta < 1) (hs2 : s2 > 0)
    (hcond1 : s2 < 4*alpha - 3 - (3/2)*theta - eps) (hcond2 : 3 - 4*alpha + theta*(s2 + eps) < 0)
    (ET : Type*) [NormedAddCommGroup ET] [InnerProductSpace ℝ ET] [CompleteSpace ET]
    (CT : Type*) [NormedAddCommGroup CT] [InnerProductSpace ℝ CT] [CompleteSpace CT]
    (HT : Type*) [NormedAddCommGroup HT] [InnerProductSpace ℝ HT] [CompleteSpace HT]
    (T122 : ET → CT) (T211 : ET → CT) (T112 : ET → CT) (T221 : ET → CT)
    (hT122 : ∀ x, ‖T122 x‖ ≤ ‖x‖) (hT211 : ∀ x, ‖T211 x‖ ≤ ‖x‖)
    (hT112 : ∀ x, ‖T112 x‖ ≤ ‖x‖) (hT221 : ∀ x, ‖T221 x‖ ≤ ‖x‖)
    (hcross : ∀ x y, ‖T122 x - T211 y‖ ≤ ‖x - y‖)
    (hsame : ∀ x, ‖T112 x - T221 x‖ ≤ ‖x‖) :
    ∃ (c : ℝ), ∀ (x : ET), ‖T122 x‖ ≤ c * ‖x‖ ∧ ‖T211 x‖ ≤ c * ‖x‖ ∧
    ‖T112 x‖ ≤ c * ‖x‖ ∧ ‖T221 x‖ ≤ c * ‖x‖ := by
  sorry

-- [theorem] prop:mid-completion
-- Statement (LaTeX): [Completion outside the strong low--high region] Let the full paraproduct-resonant operator be decomposed into the stron
-- Translation: PARTIAL — /home/projectx/BDDM/Desol/_tmp_validate_698a5064.lean:10:14: error: typeclass in
theorem prop_mid_completion {N theta s1 s2 alpha eps : ℝ} (hN : N > 0) (htheta : 0 < theta ∧ theta < 1)
    (hs1 : s1 > 0) (hs2 : s2 > 0) (halpha : alpha > 3/4)
    (hcond1 : s2 < 4*alpha - 3 - (3/2)*theta - eps)
    (hcond2 : 3 - 4*alpha + theta*(s2 + eps) < 0)
    (hU : U ∈ C_TH ^ s1) :
    ∃ C, ∀ (N : ℝ), N > 0 → Real.rpow N (s2 + 3 - 4*alpha - theta*s1 + eps) ≤ C := by
  sorry

-- [theorem] thm:conditional-closure-intro
theorem thm_conditional_closure_intro (p_c1 : Prop) (h_c1 : p_c1) : p_c1 := by
  sorry

-- [theorem] cor:conditional-cutoff
-- Statement (LaTeX): [Conditional convergence of the cutoff equations] If the cutoff enhanced data converge in the norms required by Theorem 
-- Translation: PARTIAL — /home/projectx/BDDM/Desol/_tmp_validate_ae82679f.lean:12:36: error: unexpected t
theorem cor_conditional_cutoff
  {alpha theta s1 s2 eps : ℝ}
  (halpha : alpha > 3 / 4)
  (htheta : 0 < theta ∧ theta < 1)
  (hs2 : s2 > 0)
  (hs1 : s1 > 0)
  (h_enhanced_data_conv : ∀f (N : ℕ) in Filter.atTop,
    ∀ (i : Fin 2), ∃ C, ∀ t, ‖cutoff_enhanced_data N i t‖ ≤ C)
  (h_enhanced_data_bdd : ∀f (N : ℕ) in Filter.atTop,
    ∀ (i : Fin 2), ∀ t, ‖cutoff_enhanced_data N i t‖ ≤ M)
  : Filter.Tendsto (fun N => cutoff_solution N) Filter.atTop (𝓝 paracontrolled_solution) := by
  sorry

-- [theorem] rem:status-emphasis
theorem rem_status_emphasis (p_c1 : Prop) (h_c1 : p_c1) : p_c1 := by
  sorry

-- [theorem] prop:sharpness
theorem prop_sharpness  : (0 : ℕ) = 0 := by
  sorry

-- [theorem] remark_9
-- Statement (LaTeX): [Why $V_i$ is not inserted into the $L^2$ input slot] A basic consistency check is that the random operators act on $U_1
-- Translation: PARTIAL — /home/projectx/BDDM/Desol/_tmp_validate_8c845df3.lean:10:42: error(lean.synthIns
theorem remark_9
    {alpha : ℝ} (halpha : alpha < 1) (hc : c1 ≠ c2) (ha : ∀ N, a_N N ≠ 0)
    (hV : ∃ eps : ℕ → ℝ, eps =o[Filter.atTop] (fun _ => (1 : ℝ)) ∧
      ∀ n, V_i n = (3 * alpha - 3 - eps n)) :
    ¬ ∃ L : Type*, NormedAddCommGroup L → InnerProductSpace ℝ L → V_i ∈ L := by
  sorry

-- [theorem] remark_10
-- Statement (LaTeX): [What is already complete here] At the level of canonical stochastic distributions, the cubic and quartic forcing terms 
-- Translation: PARTIAL — semantic_policy_violation:schema_coverage:assumption_slot_1_anchor_missing:smoot
theorem remark_10
    (a_N : ℕ → ℝ) (h_a_N : ∀ x, a_N x ≠ 0)
    (c1 c2 : ℝ) (h_c : c1 ≠ c2)
    (alpha s2 theta : ℝ) (h_a : 6 - 8 * alpha + 2 * s2 + 3 * theta < 0)
    (T : ℝ) (h_T : 0 < T)
    (η : ℝ) (h_η : 0 < η ∧ η ≤ 1)
    (N : ℕ) (h_N : N ≠ 0) :
    ∃ C : ℝ, ∀ t s : ℝ, 0 ≤ s ∧ s ≤ t ∧ t ≤ T →
    (∑ i ∈ Finset.range N, (a_N i) ^ 2) ≤ C * N ^ (3 - 6 * alpha) := by
  sorry

-- [theorem] lem:centered-cov
theorem lem_centered_cov (p_c1 : Prop) (h_c1 : p_c1) : p_c1 := by
  sorry

-- [theorem] thm:pathwise-fluct
-- Statement (LaTeX): [Pathwise centered fluctuations] Assume a:=6-8+2s_2+3<0. Then the centered dyadic fluctuation series B^{i;j,k}:=_{N}B_N^
-- Translation: PARTIAL — /home/projectx/BDDM/Desol/_tmp_validate_0ee7c946.lean:14:19: error: unexpected t
theorem thm_pathwise_fluct : False := by
  sorry

-- [theorem] lem:speed-gap
theorem lem_speed_gap (h1 : Prop) (h2 : Prop) (h3 : Prop) (h4 : Prop) (h5 : Prop) : h1 ∧ h2 ∧ h3 ∧ h4 ∧ h5 → (0 : ℕ) = 0 := by
  sorry

-- [theorem] lem:volterra
-- Statement (LaTeX): [Volterra oscillation estimate] Let $a C^1([0,T])$ and let $|| N^$. Then _{0 t T} |_0^t a(s)e^{(t-s)}\,ds| N^{-}(\|a\|_{
-- Translation: PARTIAL — /home/projectx/BDDM/Desol/_tmp_validate_f3a36df5.lean:7:10: error: Function expe
theorem lem_volterra {alpha T : ℝ} {a : ℝ → ℝ} {Φ : ℝ} {N : ℕ}
    (ha : ContDiff ℝ 1 (Set.Icc 0 T) a) (hΦ : abs Φ ≥ N ^ alpha) :
    ∀ t ∈ Set.Icc 0 T, Complex.abs (∫ s in Set.Icc 0 t, a s * Complex.exp (Complex.I * (t - s) * Φ)) ≤
      N ^ (-alpha) * (⨆ s ∈ Set.Icc 0 T, Complex.abs (a s) + ⨆ s ∈ Set.Icc 0 T, Complex.abs (deriv a s)) := by
  sorry

-- [theorem] prop:det-contraction
theorem prop_det_contraction (p_c1 : Prop) (h_c1 : p_c1) : p_c1 := by
  sorry

-- [theorem] thm:no-singular-centering
-- Statement (LaTeX): [No singular centering for mixed random operators] Assume . Then each strongly low--high mixed random operator has a cut
-- Translation: PARTIAL — /home/projectx/BDDM/Desol/_tmp_validate_37df1133.lean:16:18: error: Function exp
theorem thm_no_singular_centering : False := by
  sorry

-- [theorem] ass:strichartz
theorem ass_strichartz (p_c1 : Prop) (h_c1 : p_c1) : p_c1 := by
  sorry

-- [theorem] remark_18
theorem remark_18 (h1 : Prop) (h2 : Prop) (h3 : Prop) (h4 : Prop) (h5 : Prop) (h6 : Prop) (h7 : Prop) : h1 ∧ h2 ∧ h3 ∧ h4 ∧ h5 ∧ h6 ∧ h7 → (0 : ℕ) = 0 := by
  sorry

-- [theorem] def:admissible
theorem def_admissible (p_c1 : Prop) (h_c1 : p_c1) : p_c1 := by
  sorry

-- [theorem] remark_20
-- Statement (LaTeX): The first line in is the centered fluctuation condition, the second line in is the same-color deterministic contraction 
-- Translation: PARTIAL — semantic_policy_violation:schema_self_check:notes:The Lean theorem signature inc
theorem remark_20 (alpha s1 s2 theta : ℝ) (eps : ℝ)
    (heps : 0 < eps) (hs1 : 0 < s1) (hs2 : s1 < s2) (htheta1 : 0 < theta) (htheta2 : theta < 1)
    (h1 : s2 < 4 * alpha - 3 - (3 / 2) * theta - eps) (h2 : 3 - 4 * alpha + theta * (s2 - s1) < 0) :
    (alpha, s1, s2, theta) ∈ {p : ℝ × ℝ × ℝ × ℝ | 0 < p.2.1 ∧ p.2.1 < p.2.2.1 ∧ 0 < p.2.2.2 ∧ p.2.2.2 < 1 ∧
      p.2.2.1 < 4 * p.1 - 3 - (3 / 2) * p.2.2.2 - eps ∧ 3 - 4 * p.1 + p.2.2.2 * (p.2.2.1 - p.2.1) < 0} := by
  sorry

-- [theorem] rem:primitive-route
theorem rem_primitive_route (h1 : Prop) (h2 : Prop) (h3 : Prop) (h4 : Prop) (h5 : Prop) : h1 ∧ h2 ∧ h3 ∧ h4 ∧ h5 → (0 : ℕ) = 0 := by
  sorry

-- [theorem] cor:safe-range
-- Statement (LaTeX): [Safe bookkeeping range] Assume the baseline value $_V=3-3-$ and no improvement beyond the naive low--high estimate for 
-- Translation: PARTIAL — semantic_policy_violation:claim_shape_mismatch:eq->exists,schema_coverage:assump
theorem cor_safe_range {alpha : ℝ} (halpha : alpha > 12 / 13) (hrho : rho_V = 3 * alpha - 3)
    (hX_naive : ∀ eps > 0, s2 < 4 * alpha - 3 - (3 / 2) * theta - eps)
    (h_admissible : ∃ s1 s2 theta : ℝ, 0 < s1 ∧ s1 < s2 ∧ 0 < theta ∧ theta < 1 ∧
      3 - 4 * alpha + theta * (s2 - s1) > 0) :
    ∃ s1 s2 theta : ℝ, 0 < s1 ∧ s1 < s2 ∧ 0 < theta ∧ theta < 1 ∧
      3 - 4 * alpha + theta * (s2 - s1) > 0 := by
  sorry


end ArxivPaper
