-- Auto-generated by arxiv_to_lean.py
-- Paper: 2604.21821
-- Generated: 2026-04-26 06:45 UTC

import Desol.SDE.Basic

open MeasureTheory ProbabilityTheory

-- Suppress binder-annotation check: some auto-translated typeclasses may not
-- be recognized as class instances by Lean's binder checker, but are harmless.
set_option checkBinderAnnotations false

namespace ArxivPaper

-- [theorem] th:lions
theorem th_lions (h1 : Prop) (h2 : Prop) : (let Claim : Prop := h1 ∧ h2; Claim) := by
  sorry

-- [theorem] theorem_2
-- Statement (LaTeX): The space \( H^1_{D,f}(0,z_F) \) is a Hilbert space with respect to the norm \[ \|v\|_{D,f}^1 = ( _0^{z_F} f(z) v^2(z) \
-- Translation: PARTIAL — /home/projectx/BDDM/Desol/_tmp_validate_a12e6f1c.lean:8:39: error: unexpected to
theorem theorem_2 (f D : ℝ → ℝ) (z_F : ℝ) (hf : ∀ z ∈ Set.Icc 0 z_F, 0 < f z)
    (hD : LipschitzContinuous D) :
    let H1_Df := { v : ℝ → ℝ | v ∈ L2_f(0, z_F) ∧ v_z_weak ∈ L2_D(0, z_F) }
    let norm_H1_Df (v : ℝ → ℝ) := Real.sqrt (∫ z in Set.Icc 0 z_F, f z * v z ^ 2 + ∫ z in Set.Icc 0 z_F, D z * (deriv v z) ^ 2)
    IsComplete H1_Df norm_H1_Df := by
  sorry

-- [theorem] theorem_3
-- Statement (LaTeX): The set of test functions is a closed subspace of $H^1_{D,f}$, $$=\{v H^1_{D,f}(0,z_F)\,|\, v(0)=0\} H^1_{D,f}. $$ i.e. 
-- Translation: PARTIAL — /home/projectx/BDDM/Desol/_tmp_validate_aee20f0e.lean:9:37: error: Application t
theorem theorem_3 {alpha : Type*} [MeasurableSpace alpha] [Fintype alpha]
    (f D : alpha → ℝ) (z_F : alpha) (hf : ∀ z, f z > 0) (hD : ∀ z, D z > 0)
    (H1_D_f : Type*) [NormedAddCommGroup H1_D_f] [InnerProductSpace ℝ H1_D_f]
    (eval_zero : ContinuousLinearMap ℝ H1_D_f ℝ) (T : Set H1_D_f)
    (hT : T = {v : H1_D_f | eval_zero v = 0})
    (h_dense : DenseRange eval_zero)
    (h_complete : CompleteSpace H1_D_f)
    (h_closed : IsClosed (Set.range eval_zero)) :
    IsClosed T := by
  sorry

-- [theorem] rem
theorem rem (h1 : Prop) (h2 : Prop) : h1 ∧ h2 → (0 : ℕ) = 0 := by
  sorry

-- [theorem] th:WPICa
theorem th_WPICa (h1 : Prop) (h2 : Prop) : (let Claim : Prop := h1 ∧ h2; Claim) := by
  sorry

-- [theorem] lem:tc
-- Statement (LaTeX): $=\{v H^1_{D,f}(0,z_F)\,|\, v(0)=0\} C_a(0,z_F) $
-- Translation: PARTIAL — semantic_repair_invalid:/home/projectx/BDDM/Desol/_tmp_validate_fdda8525.lean:16
theorem lem_tc {alpha : Type*} [NormedAddCommGroup alpha] [NormedSpace ℝ alpha]
    (v : alpha) (h1 : v ∈ {w : alpha | ∃ (hw : w ∈ Set.univ), True})
    (h2 : ∃ (z_F : ℝ), True)
    (h3 : ∃ (C_a : Set alpha), True)
    (h4 : ∃ (H1_D_f : Set alpha), True)
    (h5 : v ∈ {w : alpha | ∃ (hw : w ∈ H1_D_f), True})
    (h6 : v ∈ {w : alpha | ∃ (hw : w ∈ Set.univ), True})
    (h7 : ∃ (f : ℝ → ℝ), ∀ z, z ∈ Set.Ioo 0 z_F → f z > 0)
    (h8 : ∃ (D : ℝ → ℝ), ∀ z, z ∈ Set.Ioo 0 z_F → D z > 0)
    (h9 : v ∈ {w : alpha | ∃ (hw : w ∈ Set.univ), True})
    : v ∈ {w : alpha | ∃ (hw : w ∈ C_a), True} := by
  sorry

-- [theorem] cor:wpi
theorem cor_wpi (h1 : Prop) (h2 : Prop) : (let Claim : Prop := h1 ∧ h2; Claim) := by
  sorry

-- [theorem] eq:zf
-- Statement (LaTeX): Assume that the condition is satisfied. Then the following inequality |v(z)| C_0 \|v\|_{D, f}, z [0, z_F], holds for all
-- Translation: PARTIAL — /home/projectx/BDDM/Desol/_tmp_validate_bfa4b5ad.lean:9:13: error: unexpected to
theorem eq_zf {alpha : Type*} [NormedAddCommGroup alpha] {v : alpha} {f D : ℝ → ℝ}
    {z_F : ℝ} {C0 : ℝ} (hf : ∀ z ∈ Set.Icc 0 z_F, 0 < f z)
    (hD : LipschitzWith (1 : ℝ) D) (hcond : ∀ z ∈ Set.Ioo 0 z_F,
    ∃ C, ∀f x in Filter.atTop, |(z_F - z) * ∫ x ∈ Set.Icc 0 z, 1 / D x| ≤ C * 1)
    (hv : v ∈ {v : alpha | ∃ (h : v ∈ Set.Icc 0 z_F), True}) :
    ∀ z ∈ Set.Icc 0 z_F, Real.sqrt (f z) * ‖v‖ ≤ C0 * ‖v‖ := by
  sorry

-- [theorem] th:4g
theorem th_4g (h1 : Prop) : (let Claim : Prop := h1; Claim) := by
  sorry

-- [theorem] lemm:M
-- Statement (LaTeX): The triadiagonal mass matrix $M$ is a symmetric positive definite matrix.
-- Translation: PARTIAL — semantic_repair_invalid:/home/projectx/BDDM/Desol/_tmp_validate_4d117f0f.lean:7:
theorem lemm_M (n : ℕ) (hn : 1 < n) (M : Matrix (Fin (n - 1)) (Fin (n - 1)) ℝ) :
    M.IsSymm ∧ M.IsPosDef := by
  sorry

-- [theorem] lemm:Mf
-- Statement (LaTeX): Given that $f(z) 0$, then the tridiagonal weighted mass matrix $M_f$ is symmetric positive definite. Moreover, the appro
-- Translation: PARTIAL — /home/projectx/BDDM/Desol/_tmp_validate_04bd781c.lean:9:51: error: Function expe
theorem lemm_Mf
  {n : ℕ} {f : ℝ → ℝ} (hf : ∀ z, f z ≥ 0) :
  let M_f : Matrix (Fin (n - 1)) (Fin (n - 1)) ℝ :=
    fun i j => ∫ z in Set.Icc 0 1, f z * (fun i => phi (i + 1) z) i * (fun j => phi (j + 1) z) j
  (∀ i j, M_f i j = M_f j i) ∧ (∀ y : Fin (n - 1) → ℝ, y ≠ 0 → 0 < ∑ i, ∑ j, y i * M_f i j * y j) := by
  sorry

-- [theorem] lemma:2.8
-- Statement (LaTeX): Assuming $f(z) 0$ is a strictly decreasing positive function, then the tridiagonal matrix $K_f$ is positive definite and
-- Translation: PARTIAL — semantic_policy_violation:claim_shape_mismatch:ineq->forall,schema_coverage:assu
theorem lemma_2_8 {n : ℕ} {f : ℝ → ℝ} {K_f : Matrix (Fin (n - 1)) (Fin (n - 1)) ℝ} {B : Matrix (Fin (n - 1)) (Fin (n - 1)) ℝ}
    (hf_nonneg : ∀ z, 0 ≤ f z) (hf_decr : StrictAnti f) (hf_pos : ∀ z, 0 < f z) :
    (∀ y : Fin (n - 1) → ℝ, 0 < ∑ i : Fin (n - 1), ∑ j : Fin (n - 1), y i * y j * K_f i j) ∧
    (∀ y : Fin (n - 1) → ℝ, 0 ≤ ∑ i : Fin (n - 1), ∑ j : Fin (n - 1), y i * y j * B i j) := by
  sorry

-- [theorem] lemm:SD
-- Statement (LaTeX): Given that $D(z) 0$, then the tridiagonal diffusion matrix $S(D)$ is symmetric. Assuming that $D(z) > 0$ is strictly pos
-- Translation: PARTIAL — semantic_repair_invalid:/home/projectx/BDDM/Desol/_tmp_validate_94b8b3b9.lean:6:
theorem lemm_SD:SD (D : ℝ → ℝ) (hD_nonneg : ∀ z, D z ≥ 0) (hD_pos : ∀ z ∈ Set.Ico 0 1, D z > 0) :
  let S := fun (i j : Fin (n - 1)) => ∫ z in Set.Icc 0 1, D z * (deriv (fun x => x) z) * (deriv (fun x => x) z)
  let S_approx := fun (i j : Fin (n - 1)) => ∫ z in Set.Icc 0 1, D z * (deriv (fun x => x) z) * (deriv (fun x => x) z)
  (∀ i j, S i j = S j i) ∧
  (∀ y : Fin (n - 1) → ℝ, 0 < ∑ i, ∑ j, y i * y j * S i j) ∧
  (∀ y : Fin (n - 1) → ℝ, 0 < ∑ i, ∑ j, y i * y j * S_approx i j) := by
  sorry

-- [theorem] lemma_14
-- Statement (LaTeX): Assuming $D(z)$ is a strictly decreasing positive function, then the tridiagonal matrix $A(D)$ is positive definite.
-- Translation: PARTIAL — /home/projectx/BDDM/Desol/_tmp_validate_7c0f4ec3.lean:11:31: error(lean.synthIns
theorem lemma_14
  {n : ℕ} (D : ℝ → ℝ) (A : Matrix (Fin n) (Fin n) ℝ)
  (hD_pos : ∀ z, D z > 0)
  (hD_decr : ∀ z1 z2, z1 < z2 → D z2 < D z1)
  (hA : ∀ i j, A i j = ∫ z in Set.Icc 0 1, D z * (deriv (fun x => x) z) * (deriv (fun x => x) z))
  (hA_tridiag : ∀ i j, i ≠ j ∧ |i - j| ≠ 1 → A i j = 0) :
  ∀ y : Fin n → ℝ, y ≠ 0 → 0 < ∑ i : Fin n, ∑ j : Fin n, y i * y j * A i j := by
  sorry

-- [theorem] rem:fh
-- Statement (LaTeX): For a fixed small $h>0$ , let $$ _{h} = _{z [0,1-h]} f(z),$$ then $ _{h} > 0$ since $[0,1-h] [0,1)$ and $f(z)>0$ over $[
-- Translation: PARTIAL — semantic_policy_violation:schema_coverage:expected_at_least_4_assumption_hypothe
theorem rem_fh (f : ℝ → ℝ) (h : ℝ) (f_min : ℝ) (z_F : ℝ)
    (h_pos : h > 0) (h_subset : Set.Icc 0 (1 - h) ⊆ Set.Icc 0 1)
    (f_pos : ∀ z ∈ Set.Icc 0 1, f z > 0) (f_zF_pos : f z_F > 0) :
    let f_h := ⨅ z ∈ Set.Icc 0 (1 - h), f z
    f_h > 0 ∧ f_h ≥ f_min ∧ f_min > 0 := by
  sorry

-- [theorem] lemma:m
-- Statement (LaTeX): Assume that $f(z) 0$ satisfies and that $ t < {6}{T_e}$, then $$y^tM_fy - {z_F} t y^tK_fy \;>\; _{h} }{24} \| y \|_{h}^2
-- Translation: PARTIAL — semantic_policy_violation:schema_coverage:assumption_slot_2_anchor_missing:satis
theorem lemma_m {n : ℕ} (f : ℝ → ℝ) (deltat h z_F T_e : ℝ) (y : Fin (n - 1) → ℝ)
    (K_f M_f : Matrix (Fin (n - 1)) (Fin (n - 1)) ℝ) (f_h : ℝ)
    (hf : f_h > 0) (hdeltat : deltat < (h / (6 * F)) * (z_F / T_e)) (hy : y ≠ 0)
    (hA10 : ∀ z ∈ Set.Icc 0 1, f z ≥ 0) :
    (∑ i : Fin (n - 1), ∑ j : Fin (n - 1), y i * M_f i j * y j) -
    (T_e / z_F) * deltat * (∑ i : Fin (n - 1), ∑ j : Fin (n - 1), y i * K_f i j * y j) >
    (f_h / 24) * (∑ i : Fin (n - 1), (y i)^2 * h) ∧
    (f_h / 24) * (∑ i : Fin (n - 1), (y i)^2 * h) ≥
    (f_h / 24) * (∑ i : Fin (n - 1), ∑ j : Fin (n - 1), y i * M_f i j * y j) := by
  sorry

-- [theorem] lemma:g
theorem lemma_g (h1 : Prop) (h2 : Prop) : (let Claim : Prop := h1 ∧ h2; Claim) := by
  sorry

-- [theorem] theorem_18
theorem theorem_18 (h1 : Prop) (h2 : Prop) : (let Claim : Prop := h1 ∧ h2; Claim) := by
  sorry


end ArxivPaper
